### ISSUE TITLE
Making a Declarative Interface?

### ISSUE THREAD

**Issue by pyros2097** [andlabs/ui#102]
I'm planning on creating a declarative UI for this library like this https://github.com/lxn/walk. Do you know how I can go about this? Is there some abstraction layer that I can use?

**Comment by elimisteve** [comment]
+1 It would be nice to be able to declaratively define UIs.

**Comment by andlabs** [comment]
I don't know what a good declarative interface would be.

That being said, it is far easier to write a declarative interface on top of a non-declarative one than vice versa. Maybe ui can have one as a subpackage or something.

**Comment by andlabs** [comment]
Merged with #276.
