### ISSUE TITLE
Windows 7 64bit - WidgetGallery example freezes and stops working

### ISSUE THREAD

**Issue by VladimirMarkelov** [andlabs/ui#103]
BasicWindow example works great. But when I run WidgetGallery one, it freezes for about a second or two and Windows shows an error as if the example crashed (nothing is written to console):
![ui_freeze](https://cloud.githubusercontent.com/assets/1577186/9067865/cfb8a68e-3a94-11e5-83d1-f6b3df9b44a2.png)

**Comment by andlabs** [comment]
I'm not sure if it's freezing during table rendering or not. Can you run it in a debugger?

We'll have to see if the problem persists with libui.

**Comment by VladimirMarkelov** [comment]
If I comment out two lines in main.go:
```
@@ -40,8 +40,8 @@ func initGUI() {
        icons := readIcons()
        table := ui.NewTable(reflect.TypeOf(icons[0]))
        table.Lock()
-       d := table.Data().(*[]icon)
-       *d = icons
+       //d := table.Data().(*[]icon)
+       //*d = icons
        table.Unlock()
```
The demo works. But there is side effect: bottom area does not display any icon.

if I ran compiled original application (command to build = go build -ldflags "-w" -gcflags "-N -l" main.go icons.go) under gdb. It stopped with:
```
(gdb) run
[New Thread 15716.0x1c5c]
[New Thread 15716.0x3464]
[New Thread 15716.0x456c]
warning: Critical error detected c0000374
```

Stack trace:

```
(gdb) bt
#0  0x00000000777bfc22 in ntdll!RtlUnhandledExceptionFilter ()
   from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00000000777c0266 in ntdll!EtwEnumerateProcessRegGuids ()
   from C:\Windows\SYSTEM32\ntdll.dll
#2  0x00000000777c1472 in ntdll!RtlQueryProcessLockInformation ()
   from C:\Windows\SYSTEM32\ntdll.dll
#3  0x00000000777c3154 in ntdll!RtlLogStackBackTrace ()
   from C:\Windows\SYSTEM32\ntdll.dll
#4  0x000000007775afed in ntdll!RtlIsDosDeviceName_U ()
   from C:\Windows\SYSTEM32\ntdll.dll
#5  0x000007feff7710c8 in msvcrt!free () from C:\Windows\system32\msvcrt.dll
#6  0x0000000000424278 in asmcgocall ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by VladimirMarkelov** [comment]
Sorry, I accidentally clicked 'close and submit'.

**Comment by andlabs** [comment]
No longer relevant to the current version of package ui.
