### ISSUE TITLE
OnEnter or similar?

### ISSUE THREAD

**Issue by tikiking1** [andlabs/ui#104]
Is there a way to bind a function to Enter/Return being typed on a TextField?

**Comment by andlabs** [comment]
I've been thinking about it. It could happen. I'd have to look up the interplay between the Enter key and Windows dialogs, though.

**Comment by andlabs** [comment]
notes to self: http://blogs.msdn.com/b/oldnewthing/archive/2006/10/12/819674.aspx

**Comment by andlabs** [comment]
Migrated to https://github.com/andlabs/libui/issues/1
