### ISSUE TITLE
So many warnings on install..

### ISSUE THREAD

**Issue by amaxcz** [andlabs/ui#105]
go version go1.4.2 darwin/amd64

uname says
Darwin beruska.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64

so trying ...
go get andlabs/ui

and watching ... sadly so many warnings...
<pre>
package andlabs/ui: unrecognized import path "andlabs/ui"
beruska:test amaxcz$ go get github.com/andlabs/ui
# github.com/andlabs/ui
../go/src/github.com/andlabs/ui/basicctrls_darwin.m:280:9: warning: returning 'const char *' from a function with result type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
# github.com/andlabs/ui
../go/src/github.com/andlabs/ui/dialog_darwin.m:24:4: warning: implicit declaration of function 'finishOpenFile' is invalid in C99 [-Wimplicit-function-declaration]
# github.com/andlabs/ui
../go/src/github.com/andlabs/ui/spinbox_darwin.m:48:19: warning: local declaration of 'minimum' hides instance variable [-Wshadow-ivar]
../go/src/github.com/andlabs/ui/spinbox_darwin.m:49:19: warning: local declaration of 'maximum' hides instance variable [-Wshadow-ivar]
../go/src/github.com/andlabs/ui/spinbox_darwin.m:50:17: warning: incompatible integer to pointer conversion sending 'NSInteger' (aka 'long') to parameter of type 'id' [-Wint-conversion]
/System/Library/Frameworks/AppKit.framework/Headers/NSDictionaryController.h:23:22: note: passing argument to parameter 'value' here
../go/src/github.com/andlabs/ui/spinbox_darwin.m:52:31: warning: sending 'goSpinbox *' to parameter of incompatible type 'id<NSTextFieldDelegate>'
/System/Library/Frameworks/AppKit.framework/Headers/NSTextField.h:40:47: note: passing argument to parameter 'anObject' here
../go/src/github.com/andlabs/ui/spinbox_darwin.m:61:16: warning: local declaration of 'value' hides instance variable [-Wshadow-ivar]
../go/src/github.com/andlabs/ui/spinbox_darwin.m:86:17: warning: incompatible integer to pointer conversion sending 'NSInteger' (aka 'long') to parameter of type 'id' [-Wint-conversion]
/System/Library/Frameworks/AppKit.framework/Headers/NSDictionaryController.h:23:22: note: passing argument to parameter 'value' here
../go/src/github.com/andlabs/ui/spinbox_darwin.m:92:17: warning: incompatible integer to pointer conversion sending 'NSInteger' (aka 'long') to parameter of type 'id' [-Wint-conversion]
/System/Library/Frameworks/AppKit.framework/Headers/NSDictionaryController.h:23:22: note: passing argument to parameter 'value' here
../go/src/github.com/andlabs/ui/spinbox_darwin.m:59:29: warning: conflicting parameter types in implementation of 'setValue:': 'id' vs 'NSInteger' (aka 'long') [-Wmismatched-parameter-types]
/System/Library/Frameworks/AppKit.framework/Headers/NSDictionaryController.h:23:22: note: previous definition is here
../go/src/github.com/andlabs/ui/spinbox_darwin.m:124:33: warning: incompatible integer to pointer conversion sending 'NSInteger' (aka 'long') to parameter of type 'id' [-Wint-conversion]
/System/Library/Frameworks/AppKit.framework/Headers/NSDictionaryController.h:23:22: note: passing argument to parameter 'value' here
# github.com/andlabs/ui
../go/src/github.com/andlabs/ui/uitask_darwin.m:32:24: warning: instance method '-doKeyDown:' not found (return type defaults to 'id') [-Wobjc-method-access]
../go/src/github.com/andlabs/ui/uitask_darwin.m:32:13: warning: incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id' [-Wint-conversion]
../go/src/github.com/andlabs/ui/uitask_darwin.m:35:24: warning: instance method '-doKeyUp:' not found (return type defaults to 'id') [-Wobjc-method-access]
../go/src/github.com/andlabs/ui/uitask_darwin.m:35:13: warning: incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id' [-Wint-conversion]
../go/src/github.com/andlabs/ui/uitask_darwin.m:38:24: warning: instance method '-doFlagsChanged:' not found (return type defaults to 'id') [-Wobjc-method-access]
../go/src/github.com/andlabs/ui/uitask_darwin.m:38:13: warning: incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id' [-Wint-conversion]
</pre>

**Comment by andlabs** [comment]
Yeah, the current ui codebase does a few iffy things on OS X; the libui codebase does not, and has few, if any, warnings.

**Comment by andlabs** [comment]
No longer relevant to the current version of package ui.
