### ISSUE TITLE
Themes?

### ISSUE THREAD

**Issue by odewahn** [andlabs/ui#106]
Hi.  Thanks for this amazing project -- it's really great.  

The README hints that there are different themes available: "The example widget gallery on GTK+ in the Adwaita theme (3.13/master)".  I can't find any documentation on these, though.  Is there a way to change themes, or create new ones?

Any pointers appreciated!

**Comment by andlabs** [comment]
Those are GTK+ themes. Adwaita is the GTK+ 3 default theme. There's a number of others. ui itself doesn't provide theming; the OS does all the work.

**Comment by odewahn** [comment]
Great -- thanks for the clarification.  That totally make sense.
