### ISSUE TITLE
Build on Linux fails

### ISSUE THREAD

**Issue by dodona2** [andlabs/ui#109]
gcc errors for preamble:
../..//src/github.com/andlabs/ui/areahandler.go:7:35: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
 // static inline void uiAreaHandler *allocAreaHandler(void)

mint:17.3
ubuntu:14.04.3 LTS, Trusty Tahr
kernel:Linux INDRA 3.16.0-38-generic

**Comment by andlabs** [comment]
Yes, the Area code is incomplete. I'll fix it later today or tomorrow (and post build instructions because even if I fix these build errors you still won't be able to build it with just go get).

**Comment by dodona2** [comment]
now we gwt:

1::github.com/andlabs/ui: go build
# github.com/andlabs/ui
./areahandler.go: In function ‘allocAreaHandler’:
./areahandler.go:11:26: warning: incompatible implicit declaration of built-in function ‘malloc’ [enabled by default]
 //  ah = (uiAreaHandler *) malloc(sizeof (uiAreaHandler));
                          ^
./areahandler.go: In function ‘freeAreaHandler’:
./areahandler.go:19:3: warning: incompatible implicit declaration of built-in function ‘free’ [enabled by default]
 //  free(ah);
   ^
# github.com/andlabs/ui
/tmp/go-build326067693/github.com/andlabs/ui/_obj/areahandler.cgo2.o: In function `allocAreaHandler':
./areahandler.go:14: undefined reference to `doAreaHandlerDraw'
collect2: error: ld returned 1 exit status

adding a #include "stdlib.h" to the C code we get:
# github.com/andlabs/ui
/tmp/go-build527147078/github.com/andlabs/ui/_obj/areahandler.cgo2.o: In function `allocAreaHandler':
./areahandler.go:15: undefined reference to `doAreaHandlerDraw'
collect2: error: ld returned 1 exit status

**Comment by andlabs** [comment]
Again, you can't build this yet. It's not fully written. You'll need to wait a bit; I'll update the README when it's ready for building. Sorry.

**Comment by dodona2** [comment]
OK. ILll wait. Thanks a lot for this great work!

**Comment by dodona2** [comment]
OK, you updated README and the area handeler and I still get:

./areahandler.go: In function ‘allocAreaHandler’:
./areahandler.go:11:26: warning: incompatible implicit declaration of built-in function ‘malloc’ [enabled by default]
 //  ah = (uiAreaHandler *) malloc(sizeof (uiAreaHandler));
                          ^
./areahandler.go: In function ‘freeAreaHandler’:
./areahandler.go:19:3: warning: incompatible implicit declaration of built-in function ‘free’ [enabled by default]
 //  free(ah);
   ^
/tmp/go-build741386121/_/xxxui/_obj/areahandler.cgo2.o: In function `allocAreaHandler':
./areahandler.go:14: undefined reference to `doAreaHandlerDraw'
collect2: error: ld returned 1 exit status

**Comment by andlabs** [comment]
Oh right, I forgot to actually finish with AreaHandler. Let me get on that.

**Comment by andlabs** [comment]
Okay, it should build now. Area cannot be used yet, though, mainly because I want to make some changes to how Area scrolling works. Stay tuned.

**Comment by dodona2** [comment]
OK. it build now. Thanks a lot!

I build the short program of https://github.com/andlabs/ui/wiki/Getting-Started

Got errors: 
./main.go:19: undefined: Button
./main.go:22: undefined: Window
these are the lines involved:

       button.OnClicked(func(*Button) {
           greeting.SetText("Hello, " + name.Text() + "!")
       })
       window.OnClosing(func(*Window) bool {
           ui.Quit()
           return true
       })

**Comment by andlabs** [comment]
Oops; forgot the `ui.` in the closure parameters =P

**Comment by dodona2** [comment]
now it works. Again thanx a lot.

I'm sure you already know the gtk warnings:

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:173:38: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:185:23: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1048:2: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1053:2: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1409:22: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1497:22: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1511:22: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1943:27: No property named '-gtk-icon-transform'

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:34:8: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:76:20: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:101:16: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:126:30: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:165:20: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:207:32: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:535:16: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:555:28: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:575:27: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:725:28: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:749:40: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:773:39: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:797:39: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:875:40: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-backgrounds.css:23:30: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-backgrounds.css:53:8: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-backgrounds.css:68:8: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-backgrounds.css:92:20: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:19:7: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:26:7: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:57:23: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:79:7: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:86:7: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:113:22: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:118:22: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:123:22: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:148:22: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:153:22: Missing name of pseudo-class

(main:28025): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:158:22: Missing name of pseudo-class

**Comment by andlabs** [comment]
Nope; that's likely a problem with your GTK+ installation. I don't know what cuses it.
