### ISSUE TITLE
Help installing on os x

### ISSUE THREAD

**Issue by sharpner** [andlabs/ui#112]
hi there, 

I am trying to install the latest master on OS X. 

```
 go install github.com/andlabs/ui
can't load package: package github.com/andlabs/ui: ~/Development/Go/src/github.com/andlabs/ui/link_darwin.go: malformed #cgo argument: @executable_path
```

Any hints how to solve this issue? 

Thanks in advance, awesome project

**Comment by andlabs** [comment]
What version of Go are you using?

**Comment by sharpner** [comment]
```
$ go version
go version go1.5.2 darwin/amd64
´´´

**Comment by akamensky** [comment]
On 1.5.x I get the same error.

Tested on 1.5, 1.5.1 and 1.5.2

If downgrade to 1.4.3 the error changes to:
```
/usr/local/go/bin/go run /Users/akamensky/IdeaProjects/andlabs-ui-test/src/main.go
src/main.go:4:2: /Users/akamensky/IdeaProjects/andlabs-ui-test/src/github.com/andlabs/ui/link_darwin.go: malformed #cgo argument: -L${SRCDIR}
```

Before installation I followed the instructions to compile `libui` given in #108

**Comment by andlabs** [comment]
See the bug I linked above. It's a cgo problem. You can try editing the Go source if you want, but I don't know what negative effect it will have.

And yes, ${SRCDIR} expansion was added in 1.5. But due to [go issue 9411](https://github.com/golang/go/issues/9411) 1.4 wouldn't work anyway.

**Comment by sharpner** [comment]
installing commit #d5a93806e8a4f3dc6ad851e9c0600b9ca12d34f2 seems to work for me though.

**Comment by andlabs** [comment]
Right, but then it won't look for libui.0.dylib in the right place. You can use `otool` to see where your built executable expects libui.0.dylib; it will most likely be either an absolute path or a path relative to the *current directory*, not the executable directory. This is a Go issue; it will need to be fixed by the Go developers.

**Comment by akamensky** [comment]
@andlabs From the https://github.com/golang/go/issues/13720 it seems you are using dev branch, does it build there?

**Comment by andlabs** [comment]
No; not even the current master allows `@` in a `#cgo` line. That particular fix to package ui was done at the same time as one in libui; clearly this was all in error.

**Comment by andlabs** [comment]
Okay yeah that temporary fix did not fix anything... which is great, because OS X is now my primary OS again. Yay?

This really needs to wait for the Go bug I filed to be fixed. Sorry.

**Comment by andlabs** [comment]
The Go bug has been fixed; if you upgrade to Go master you will be able to use package ui on OS X again.

Note that in the meantime some things about what libui produces on output has changed, so if you have updated your copy of libui you will need to recreate your symlinks.

**Comment by sharpner** [comment]
thank you, I can confirm that I now works. With the current master of go (305b4baf41ecbaa3469428b7debb389bd1527804)

**Comment by sharpner** [comment]
Ok it compiles, but running the example yields this:
```
dyld: Library not loaded: @rpath/libui.A.dylib
  Referenced from: /var/folders/1h/13zdxw8d5s75s1qvm962m7bc0000gn/T/go-build567076525/command-line-arguments/_obj/exe/blub
  Reason: image not found
signal: trace/BPT trap
```

**Comment by andlabs** [comment]
Did you forget to put libui.A.dylib in the same folder?

**Comment by sharpner** [comment]
I didn't use go test, I used `go run` with the example:
```
package main

import (
	"github.com/andlabs/ui"
)

func main() {
	err := ui.Main(func() {
		name := ui.NewEntry()
		button := ui.NewButton("Greet")
		greeting := ui.NewLabel("")
		box := ui.NewVerticalBox()
		box.Append(ui.NewLabel("Enter your name:"), false)
		box.Append(name, false)
		box.Append(button, false)
		box.Append(greeting, false)
		window := ui.NewWindow("Hello", 200, 100, false)
		window.SetChild(box)
		button.OnClicked(func(*ui.Button) {
			greeting.SetText("Hello, " + name.Text() + "!")
		})
		window.OnClosing(func(*ui.Window) bool {
			ui.Quit()
			return true
		})
		window.Show()
	})
	if err != nil {
		panic(err)
	}
}
```

but even if I compile a binary and have a folder structure like this:
```
libui.0.dylib -> ../libui/out/libui.dylib
libui.dylib -> ../libui/out/libui.dylib
example
```

I get the same error.

**Comment by sharpner** [comment]
The dylib files seem to be compiled correctly:
```
$ file libui.0.dylib
libui.0.dylib: Mach-O 64-bit dynamically linked shared library x86_64
$ file libui.dylib
libui.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

**Comment by andlabs** [comment]
The same thing applies. `go run` does not run the executable from the same directory as the source; it uses a temporary work directory (as evidenced from the dyld output you got), and the `go` tool does not copy the .dylibs over to that directory before running. You will either need to

- install libui into a global path
- build (instead of run) your test program and place the executable in the same folder as the dylibs (this last part was the entire point of the `@rpath`/`@executable_path` issue that blocked this bug, for the record)

**Comment by sharpner** [comment]
like I said above, I even get the same error if I do step 2 and compile a binary

```
libui.0.dylib -> ../libui/out/libui.dylib
libui.dylib -> ../libui/out/libui.dylib
example
```

example is the compiled binary. 

Running it yields:
```
dyld: Library not loaded: @rpath/libui.A.dylib
  Referenced from: ./example
  Reason: image not found
signal: trace/BPT trap
```

I will try testing with a global path instead later. 

Thanks for now

**Comment by andlabs** [comment]
That's weird. Are you sure you're using an updated package ui? Is `-Wl,-rpath,@executable_path` in your `link_darwin.go`?

**Comment by sharpner** [comment]
yep I'm using @33f5e9b3e06f2f784d4b029c95550f902bcfea2e atm. 

But I need to test tomorrow again, had to rollback to go 1.5.2.

**Comment by akamensky** [comment]
@sharpner Any luck running it?

**Comment by sharpner** [comment]
nope. Not yet. Will wait for the stable 1.6 for now. Let me know if you could figure it out :D

**Comment by include** [comment]
any advances on this one?

**Comment by andlabs** [comment]
It should be resolved by now. You will need Go 1.6 beta 2. There's nothing I can do about that, sorry; those amount to bugs in Go and cgo.

**Comment by sharpner** [comment]
I can confirm that the confirmation works with 1.6beta2.
The other thing was probably me using it wrong ;) but I never tried it again. Waiting for 1.6 stable.

**Comment by sharpner** [comment]
Found my problem, was just a stupid renaming thing. libui.0.dylib vs libui.A.dylib. Maybe it might help someone :)
