### ISSUE TITLE
i am  build  a simple demo

### ISSUE THREAD

**Issue by wyq756543431** [andlabs/ui#113]
# github.com/andlabs/ui
../../intellijwork/gowork/src/github.com/andlabs/ui/main.go:24:2: warning: control reaches end of non-void function [-Wreturn-type]
dyld: Library not loaded: @rpath/libui.0.dylib
  Referenced from: /var/folders/ww/401_v1c518vfwpbn2dlbknqr0000gn/T/go-build705874425/command-line-arguments/_obj/exe/mian
  Reason: image not found
signal: trace/BPT trap

**Comment by andlabs** [comment]
See #112.
