### ISSUE TITLE
static linking

### ISSUE THREAD

**Issue by melias122** [andlabs/ui#114]
Do you have any plans for static linking?

**Comment by andlabs** [comment]
If there's a way I can avoid exporting non-public functions to the static library, maybe.

**Comment by andlabs** [comment]
notes to self: https://github.com/golang/go/commit/1aab7b9626b8bc735d7340c1eb47d8d46560290f

**Comment by variadico** [comment]
Would this mean we wouldn't have to lug around `libui.A.dylib`?

**Comment by andlabs** [comment]
If it happens, yes.

**Comment by andlabs** [comment]
It has happened.
