### ISSUE TITLE
Label/Remove issues that are no longer valid after the rewrite

### ISSUE THREAD

**Issue by sharpner** [andlabs/ui#115]
It would be of much help if those issues that are "pre-rewrite" are flagged somehow.

If all are still valid, than please ignore this issue :-)

**Comment by andlabs** [comment]
I will need to go through them all. Some of them are still relevant because they ask for stuff that isn't in the rewrite either, and some involve features that aren't in the rewrite yet (such as Table).

**Comment by sharpner** [comment]
Ok :) thx for the fast response.

**Comment by andlabs** [comment]
Taking care of this.
