### ISSUE TITLE
Request: Semi-Scrolling Area

### ISSUE THREAD

**Issue by duckbrain** [andlabs/ui#116]
I am trying to make a document viewer out of an `Area`. I am currently able to render the document using either a scrolling area or a non-scrolling area, but neither one gives me vertical only scrolling. 

- If I use the non-scrollnig variety I have to implement my own scrolling, but I can't seem to get scroll wheel events through the `AreaHandler`, plus no matter how hard I try it will never be OS-like.
- If I use the scrolling area, I have to define both the width and height of my content. I can calculate the height based on the width, but that means I need to use a static width because the Area gives Height and Width 0 when in scrolling mode.

I can see this implemented as a `NewVerticalScrollingArea`, but also considered it may be possible to have the scrolling area automatically scroll if one of it's dimentions were set to 0.

I can see the distiction goes down to the libui layer. I may have a look at it to see if it is something I can get working, but I don't have access to OSX to test on.

#101 talks about rewrite of the Areas, but I think that has already happened. May be able to close this

**Comment by duckbrain** [comment]
I've found a workaround by using two Areas, one scrolling, the other non-scrolling to measure the size for the scrolling one. I realized that the events could not be fired sometimes, but it is close enough for what I am doing.
https://github.com/duckbrain/uidoc/blob/master/uidoc.go#L23

**Comment by andlabs** [comment]
I'm interested in this proposal anyway, given what you are doing will be noted as undocumented behavior when I write the documentation. I'm not sure how I would implement this, to be honest, which is why I didn't act on it immediately. GTK+ and OS X both rely on being able to scroll a fixed-size widget in a scrolling window. I'm not sure what the events are to detect that the viewport size has changed. If I knew that, this could happen.

**Comment by duckbrain** [comment]
Yeah, I saw that, but it works on Linux, and that's all I'm worried about for now. I've done all of my GUI development on Windows up to this point, but it's been a few years. I like the direction the project is headed and I'd like to help out. Thanks for the work.

**Comment by andlabs** [comment]
Migrated to https://github.com/andlabs/libui/issues/82. Let me know what you think of this new design over there.
