### ISSUE TITLE
[win] cannot build wiki example

### ISSUE THREAD

**Issue by lloiser** [andlabs/ui#119]
I can't run the example in the [wiki](https://github.com/andlabs/ui/wiki/Getting-Started)

libui builds using gnu make (http://gnuwin32.sourceforge.net/packages/make.htm) even though a million warnings are displayed...
copied `libui/out/libui.dll` and `libui/ui.h` to `ui/`. 
created example in another package

So far I run almost everything with a http://mingw-w64.org (updated today) - didn't work here...

``` bash
go run example.go
# github.com/andlabs/ui
d:/programs/mingw64/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/Development/src/github.com/andlabs/ui/libui.dll when searching for -lui
d:/programs/mingw64/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/Development/src/github.com/andlabs/ui/libui.dll when searching for -lui
d:/programs/mingw64/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lui
collect2.exe: error: ld returned 1 exit status
```

I tried to install mingw using the installer of http://www.mingw.org/ - didn't work either

``` bash
go run example.go
# github.com/andlabs/ui
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
```

```
go version go1.6 windows/amd64
WIN 10 Pro 64 bit
VS 2015 Community
```

**Comment by andlabs** [comment]
As mentioned in the libui readme, you cannot currently build libui using MinGW; it must be with MSVC. Sorry. (You still need MinGW for Go, and MinGW can be used to build things that depend on libui.)

Once you do build libui, simply copy libui.dll to the github.com/andlabs/ui folder in your $GOPATH and go will build it properly.

**Comment by lloiser** [comment]
I already built the libui.dll using gnu make in a MSVC and copied both the libui.dll and the ui.h to the ui folder. This isn't the problem. But I cannot run the example neither from cmd nor MSVC ...
Should I `go run ...` from a msys cmd?

**Comment by lloiser** [comment]
I'm a bit worried that the `go run ...` the skips the built libui.dll.
```bash
d:/programs/mingw64/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/Development/src/github.com/andlabs/ui/libui.dll when searching for -lui
```

**Comment by andlabs** [comment]
Did you build a 32-bit libui.dll by mistake?

**Comment by lloiser** [comment]
using DependencyWalker I can see the following output
![image](https://cloud.githubusercontent.com/assets/3003233/13642716/e7033950-e61d-11e5-8340-cfadbdba0117.png)

seems to be 32 bit... but how did I do this?!

**Comment by andlabs** [comment]
How did you launch the MSVC command line?

**Comment by lloiser** [comment]
yes. (I have already read the https://github.com/andlabs/libui/issues/16 in libui)
reading some articles on the internet suggest using the `LDFLAGS` with `-m64`. Still fails with:
```
LINK : warning LNK4044: unrecognized option '/m64'; ignored
   Creating library out/libui.lib and object out/libui.exp
LINK : fatal error LNK1561: entry point must be defined
make[1]: *** [out/libui.dll] error 1561
make: *** [libui] error 2
```

Some more search shows that `LDFLAGS="/MACHINE:X64"` seems to be equivalent but still fails:
```
.obj/common_areaevents.c.o : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'
make[1]: *** [out/libui.dll] error 1112
make: *** [libui] error 2
```

**Comment by lloiser** [comment]
update: again after some google research I found this article: https://www.altera.com/support/support-resources/knowledge-base/solutions/rd11052014_333.html

running the vcvars64.bat has at least changed the produced dll (DependencyWalker now shows x64 instead of x86)
unfortunately it still won't run the wiki example 
```bash
D:\Development\src\github.com\andlabs\ui\example>go run example.go
exit status 3221225781
```

**Comment by lloiser** [comment]
ok it works now... the solution seems to be both or only one of the following points (but I think it is most likely the first point):

* copying the `libui.dll` to the folder where my go file is
* my antivirus software (avast) started to use a lot of cpu - disabling it seems to work. I guess the exit code 3221225781 might be some kind of timeout or so caused by some antivirus scans ...

thx for your help with 32 bit dll!

**Comment by jfcg** [comment]
see andlabs/libui#17

**Comment by andlabs** [comment]
How is that relevant to the problem here?

**Comment by itfanr** [comment]
@andlabs  could you send me a dll for win10?thanks 

bjq1016##gmail.com

**Comment by andlabs** [comment]
libui is now statically linked into package ui. Closing.
