### ISSUE TITLE
exit status -1073741515

### ISSUE THREAD

**Issue by cbxp** [andlabs/ui#121]
32-bit Windows 8.1

This library is so 'WIP' that I give up.
Even managed to build libui, but after seeing this error it's clear that this project is in very early alpha and not usable at all.

**Comment by andlabs** [comment]
Instead of opening an issue to complain about a disclaimer I repeatedly make, you could have opened an issue and actually reported actual information, such as what your panic log was, so we could fix your issues peacefully and calmly. Thanks for the criticism though! ☺️
