### ISSUE TITLE
go build ./basicwindow.go:11: undefined: ui.Do

### ISSUE THREAD

**Issue by HaoYafei-leafy** [andlabs/ui#122]
# github.com/andlabs/ui/prev/examples/basicwindow

./basicwindow.go:11: undefined: ui.Do
./basicwindow.go:13: undefined: ui.Go
./basicwindow.go:22: undefined: ui.Space
./basicwindow.go:28: cannot use func literal (type func() bool) as type func(*ui.Window) bool in argument to w.OnClosing
./basicwindow.go:30: undefined: ui.Stop

**Comment by HaoYafei-leafy** [comment]
my examples(my app )  copy libui.A.dylib and libui.dylib to myPro Folder  is ok， but  github.com/andlabs/ui/prev/examples/basicwindow.go  is  error  ? ??

**Comment by andlabs** [comment]
That example is for the old version of package ui; you can spot that by noting it's under the `prev` directory. [This example](https://github.com/andlabs/ui/wiki/Getting-Started) should work instead.

**Comment by andlabs** [comment]
prev/ no longer even exists, and the API has changed heavily since this issue was first filed, so code likely won't build anyway. Closing.
