### ISSUE TITLE
Code can't be compiled

### ISSUE THREAD

**Issue by CNLambda** [andlabs/ui#124]
Hello,
I am currently developing a desktop application on my Mac, and I wanted to switch to this library, because it seems to be better.
Here is the problem I have:
```
> go get github.com/andlabs/ui
package errors: unrecognized import path "errors" (import path does not begin with hostname)
package runtime: unrecognized import path "runtime" (import path does not begin with hostname)
package sync: unrecognized import path "sync" (import path does not begin with hostname)
package unsafe: unrecognized import path "unsafe" (import path does not begin with hostname)
```

I'll just thank you for any answers in advance,

CodenameLambda

Edit: Can you add other widgets while the program is running?

**Comment by andlabs** [comment]
Something is very wrong with your Go setup. Those are the standard packages that come with Go. I am not sure how you can fix that; you would need to describe how you installed Go.

And yes, you can add controls at runtime.

**Comment by CNLambda** [comment]
I installed go per homebrew (> brew install go), but downloading it from google and reinstalling it solved the problem.
