### ISSUE TITLE
Feature Request: Table

### ISSUE THREAD

**Issue by CNLambda** [andlabs/ui#125]
( I am using horizontal boxes inside vertical boxes, although that doesn't look like a table because the widgets don't line up )

**Comment by andlabs** [comment]
What type of table do you mean, this?

![multicolumn data table](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/TableView/Art/IntroTable_2x.png)

![grid/table control layout](http://valadoc.org/gtk+-3.0/img/example-Gtk.Grid.png)

(Both are in the works.)

**Comment by CNLambda** [comment]
I meant the first one, but the second one can be used to create the first one as well, so the second one is better ^^

But I have a little question: Is it possible to create free spaces in boxes? Or to set the width / height of elements?

**Comment by andlabs** [comment]
Second one is very different and cannot be used to make the first one. Second one is purely for laying out other controls, just like Box; it will be called Grid.

Right now the way I create empty space in a Box is to create an empty Box as a child and mark it stretchy. I haven't added a provision for setting exact widths (in fact, I've been trying to avoid doing htat, but I'm not sure how long that can go on for...).

**Comment by CNLambda** [comment]
You can create Labels to make a table with it. It is possible.

You should give the people using your library the choice between exact widths and some other options.
An implemtation could work by having functions that return the width & height, they would get the width & height of the parent as argument. Then you could define functions that return those functions for specific options, like proportional sizing.

**Comment by bcampbell** [comment]
I've been doing some work on the underlying libui table branch (my stuff is at https://github.com/bcampbell/libui/tree/table). I've just started on adding support to ui too - see https://github.com/bcampbell/ui/tree/table

(uncommented code example here: https://github.com/bcampbell/ui/blob/table/example/main.go )

Keep in mind: none of my libui stuff has been reviewed for inclusion yet, let alone the ui side of things, so don't assume that _any_ of this will stick around for the long term :-)
Any feedback much appreciated.

**Comment by andlabs** [comment]
Replaced with andlabs/libui#310.
