### ISSUE TITLE
Could not determine kind of name for C.uiAreaScrollTo

### ISSUE THREAD

**Issue by kameleon83** [andlabs/ui#128]
Hello, I have a problem when I install andlabs/ui

$ go get github.com/andlabs/ui
github.com/andlabs/ui
could not determine kind of name for C.uiAreaScrollTo

I turn with archlinux and golang 1.6

**Comment by andlabs** [comment]
Please read the README; go get by itself is insufficient while the project is being developed. (It will work once complete.)

**Comment by kameleon83** [comment]
Thanks.
