### ISSUE TITLE
Error when trying to install 

### ISSUE THREAD

**Issue by StaschikT** [andlabs/ui#129]
# github.com/andlabs/ui
Projects/Go/src/github.com/andlabs/ui/area.go:9:11: fatal error: 'ui.h' file not found
 #include "ui.h"
          ^
1 error generated.

**Comment by andlabs** [comment]
You cannot simply go get this package; you have to follow the instructions in the README.

**Comment by lostinblue** [comment]
To be fair the README just says "Needs to be written. Consult ui.h and the examples for details for now." The time you spent scolding the person you could have written the readme.

**Comment by andlabs** [comment]
You are looking at the README for libui. I'm referring to the README for package ui itself, on the main page of this repository. I apologize if that came off as scolding; that isn't the intention.

I would like to get rid of this problem outright by shipping package ui with the necessary object files, but I'd like to make things slightly more stable until then. Table and Grid won't be in for the next release, as originally planned, but if I can get what I have now working without hiccups — and I've been making a lot of headway in that department as of late — then I can get a stable release.

**Comment by andlabs** [comment]
Fixed.
