### ISSUE TITLE
It works, but a y-offset for the text would be nice

### ISSUE THREAD

**Issue by CNLambda** [andlabs/ui#130]
![image](https://cloud.githubusercontent.com/assets/18243768/15091932/88c5b172-145a-11e6-9ae1-498e3bc52f7a.png)
This is under Ubuntu, and it would be nice to fix that or to give the developer an option to change the offset. (Not just for texts, this would be *incredibly* useful)
Is there a way to tell the features to have a combined width equal to the width of the parent?

**Comment by andlabs** [comment]
That's planned, as a Form layout control. (I can't just have a fixed y-offset because it doesn't quite work that way; on GTK+ text is typically vertically centered with respect to the widget size and on OS X labels are aligned by baseline).

**Comment by andlabs** [comment]
Implemented this in libui as uiForm. I'll sync everything next packaged release.
