### ISSUE TITLE
Design questions

### ISSUE THREAD

**Issue by jfcg** [andlabs/ui#132]
Hi Pietro,
I have some questions about ui's design & thought a public issue is a good place to store this info for people that may want to learn more about internals of ui.
I am not familiar with pre-libui code either, so sorry if my questions are trivial ^_^

Why is there an exported LibuiControl() if it is only used within ui?

There seems to be two pointers in ui implementations of Control types that hold the same value. For example, in RadioButtons type there are r & c that seem to hold the same pointer value. What are their uses? Why is there two of them?

**Comment by andlabs** [comment]
`LibuiControl()` is exported so other packages can provide their own `ui.Control`s. Access ot the libui `uiControl` instance is important for containers like `ui.Window` to work properly. I forget why; you can try to reason what from looking at the implementation of `ui.Window` and so on.

However, unexported interface method names are **package local too**. If the method was unexported (`libuiControl()`), then **only the types in package `ui` can satisfy that method requirement**. (This trick is actually used by some of the Go standard packages!)

One of the goals of libui is extensibility: it should be possible to bind new OS controls to new uiControl-based types. One of my future plans is a library libuiextra and associated package `ui/extra` that provides superfluous controls. If I had not exported `LibuiControl()`, those new controls would need to be part of `ui` itself or not at all.

-----------

In the C API, some functions take a control's specific type, and some take the type `uiControl`. There are macros that do the necessary casting for you (and in the future will also do run-time type checking).

Recreating this in Go would require use of package `unsafe`, and I want to avoid using that as much as possible to ensure that this package doesn't break on future versions of Go. So I need both; this way, I can call `uiControl` methods with the `*C.uiControl` field and individual control methods with the individual control field.
