### ISSUE TITLE
when running  example on windows 10, the console did not exit 

### ISSUE THREAD

**Issue by itfanr** [andlabs/ui#133]
https://github.com/andlabs/ui/wiki/Getting-Started

 
![qq 20160523093838](https://cloud.githubusercontent.com/assets/4652694/15459174/5e2f6fb6-20d5-11e6-9859-b2af4cc68360.png)

**Comment by andlabs** [comment]
Do you mean that the console window sticks around? If so, that's already been reported; I forget the number.

**Comment by itfanr** [comment]
@andlabs  as the screenshot above showed?

**Comment by andlabs** [comment]
Oh the issue was closed, no wonder it didn't show up here

#90 has a build flag you need to pass. I'm not sure how to make it apply to all programs made with the package, or if I even can. Until then, keep all discussion there, please. Thanks!

**Comment by itfanr** [comment]
@andlabs    The solutioin that @cryptix gived worked for me as well.  https://github.com/andlabs/ui/issues/37#issuecomment-58479330
