### ISSUE TITLE
Issues on go get

### ISSUE THREAD

**Issue by CalebQ42** [andlabs/ui#134]
I've installed libui and moved the libui.so.0 to the github.com/andlabs/ui folder and symlinked it to libui.so, but now I'm getting the following error when I run go get:
`../../Go/src/github.com/andlabs/ui/combobox.go:49: cannot use _Cfunc_uiNewEditableCombobox() (type *C.struct_uiEditableCombobox) as type *C.struct_uiCombobox in assignment`

**Comment by andlabs** [comment]
API changes that I forgot to mirror in the Go code. Delete NewEditableCombobox() from combobox.go and try again. I need to add a separate ui.EditableCombobox type.

**Comment by andlabs** [comment]
Patched for now; I need to sync the API later.
