### ISSUE TITLE
Can provide more examples?

### ISSUE THREAD

**Issue by CodyGuo** [andlabs/ui#137]
Can provide more examples? Thanks

**Comment by andlabs** [comment]
What did you have in mind?

**Comment by CodyGuo** [comment]
Don't know how to use, high learning difficulty.

**Comment by sharpner** [comment]
have you seen this page? https://github.com/andlabs/ui/wiki/Getting-Started

**Comment by CodyGuo** [comment]
That was last year's tutorial, couldn't keep up with the new library.

**Comment by andlabs** [comment]
The code sample at the top is current. I haven't updated the explanations at the bottom yet.

**Comment by CodyGuo** [comment]
The library I've been waiting for a long time, haven't been able to normal use.Temporarily in LXN/walk, examples of the library is very perfect, I hope this library UI examples can also be more, easy to learn.

**Comment by lugorian** [comment]
@andlabs Maybe you can port libui examples .

**Comment by MapTo0** [comment]
Definitely more examples are needed here.
E.g. how to make a scrollable multiline textArea?
I saw the issue, I saw some commits regarding this but I can not understand how to do it.

More documentation would be great.

**Comment by andlabs** [comment]
Multiline text areas are now in libui. I need to sync the libui API with ui, but right now the libui API is being expanded to add new stuff, and there are build issues with the static libraries. Once libui Alpha 4 is released, so will a good package ui.

**Comment by physicsshark** [comment]
@andlabs I would like to see the Control Gallery example from libui ported to ui.  I would also like to see an example that used a menu.

**Comment by andlabs** [comment]
Control Gallery can be done once I can decide to stop rewriting it every few months =P (There is a new one I have locally. Not sure if I uploaded it yet.)

I didn't translate the menu API to Go yet; I want to refine it first (see andlabs/libui#152)

**Comment by physicsshark** [comment]
Thanks for letting me know.  I had been looking for the menu API in the ui package and had been unsuccessful.

**Comment by rawsh** [comment]
@andlabs can you upload the local control box? It would be very helpful

**Comment by andlabs** [comment]
Merged with andlabs/libui#317.
