### ISSUE TITLE
Can anyone tell me how to use this package step by step?

### ISSUE THREAD

**Issue by ghost** [andlabs/ui#138]
When I am trying to use this packge, problems came to me endlessly.
I hava no idea about that.
I am Chinese, if you are too, we can communicate on QQ.

**Comment by aguai** [comment]
I am studying this too... 
let me know if you got anything new
QQ:479052254
WeChat:aguaithefreak

**Comment by andlabs** [comment]
Merged with andlabs/libui#317.
