### ISSUE TITLE
Please support fullscreen toggle

### ISSUE THREAD

**Issue by henkman** [andlabs/ui#141]
It would be nice if there was a function **window.SetFullscreen(fullscreen bool)** or something of the like

**Comment by andlabs** [comment]
The functionality is automatic on OS X; just press the resize button on the titlebar.

I can definitely add a separate function to make this explicit though, on both [OS X](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWindow_Class/#//apple_ref/occ/instm/NSWindow/toggleFullScreen:) and [Windows](https://blogs.msdn.microsoft.com/oldnewthing/20050505-04/?p=35703) ([2](https://blogs.msdn.microsoft.com/oldnewthing/20100412-00/?p=14353)).

Not sure how it would be implemented on GTK+.

**Comment by henkman** [comment]
https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-fullscreen does it for gtk, just tried it.

**Comment by andlabs** [comment]
Yes, libui first.

What functionality are you thinking of that is only on two platforms?

**Comment by henkman** [comment]
I can't test on OS X is what I meant. Other people might not have a windows machine to test on. How to handle that case?

**Comment by andlabs** [comment]
I use OS X; that'll be fine I think?

**Comment by henkman** [comment]
I will try to implement this if it's ok. I have some other things that I need for a projekt of mine so I will package them into it too because they are quite closely related to this.
other features I need are:
- set/get window position
- set/get window size
- center window on screen

**Comment by andlabs** [comment]
The function should be `uiWindowToggleFullscreen()`.

**Comment by henkman** [comment]
This fine for you?

_UI_EXTERN void uiWindowSize(uiWindow *w, int *width, int *height);
_UI_EXTERN void uiWindowSetSize(uiWindow *w, int width, int height);
_UI_EXTERN void uiWindowPosition(uiWindow *w, int *x, int *y);
_UI_EXTERN void uiWindowSetPosition(uiWindow *w, int x, int y);
_UI_EXTERN void uiWindowCenter(uiWindow *w);
_UI_EXTERN void uiWindowToggleFullscreen(uiWindow *w);
_UI_EXTERN int uiWindowFullscreen(uiWindow *w);

**Comment by andlabs** [comment]
How will you implement `uiWindowFullscreen()`? I don't see such an API on OS X. Will we just keep track of that manually via the delegate? (Also that should be before `ToggleFullscreen()`.)

**Comment by henkman** [comment]
Yeah, I just keep track with a BOOL in the uiWindow struct

**Comment by andlabs** [comment]
This is now in libui. Merged with #277.
