### ISSUE TITLE
Run error on Windows 10

### ISSUE THREAD

**Issue by Archieeeeee** [andlabs/ui#142]
It shows error:
The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

**Comment by andlabs** [comment]
Strange, I thought I fixed that. I'll have to try again. What versions of go and MinGW-w64?

**Comment by Archieeeeee** [comment]
go version go1.6.2 windows/amd64

**Comment by andlabs** [comment]
https://github.com/golang/go/commit/0deb49f9c09d15bf0e4c5ec843bd374f9a377e97 related?

**Comment by emersion** [comment]
Same error here. Any ideas to workaround this?

**Comment by emersion** [comment]
Got this after running `eventvwr.msc /s`:
```
Activation context generation failed for "C:\Users\tablet-143\Desktop\Desktop.exe".Error in manifest or policy file "C:\Users\tablet-143\Desktop\Desktop.exe" on line 0. Invalid Xml syntax.
```

**Comment by emersion** [comment]
Okay. I finally found the issue. Simply renaming `static_windows_*.o` files to `.syso` fixes it, as you suggested @andlabs. Will open a PR.
