### ISSUE TITLE
Listbox

### ISSUE THREAD

**Issue by CalebQ42** [andlabs/ui#151]
Would it be possible to implement some sort of list box? Or if it's already implemented tell me what I'm overlooking.

**Comment by CalebQ42** [comment]
Since it doesn't appear there is a list box, how possible would it be for me to create a listbox using a box or Area and a bunch of lables? This is actually an important part of a program I'm working on. I would prefer to use this ui instead of gxui (nelsam fork) which is what I'm currently using (but it's starting to bust at the seams a bit).

**Comment by andlabs** [comment]
Don't do that; it'll never be like a real listbox. I'm working on a table control right now.

**Comment by c4rp3nt3r** [comment]
hi anlabs，good job！but when do you upload the table control？

**Comment by JackMordaunt** [comment]
Is there an update on the table control? I need a "ListView" / "TreeView" for my little app and I'm wondering if this is far off.

**Comment by ghiewa** [comment]
@JackMordaunt looks like lots of guys waiting for that.

**Comment by taluttasgiran** [comment]
@andlabs 👍 I'm waiting too. 😄

**Comment by bcampbell** [comment]
Duplicate of #125?

**Comment by andlabs** [comment]
Replaced with andlabs/libui#310.

**Comment by ajwillia-ms** [comment]
Hi @CalebQ42 Did you find a workaround in the meantime? I too thought about a list of labels but the mouse handling seems impossible.

A list of buttons is the best I can think of...

**Comment by andlabs** [comment]
I am working on adding tables to package ui now.

**Comment by bcampbell** [comment]
@andlabs: Doubt it's much use to you, but: https://github.com/bcampbell/ui/tree/libui-table

**Comment by andlabs** [comment]
I was going to take a different approach to specifying column types. Most of your code will work unchanged, though. I can review your code later to see if I can just use that instead.
