### ISSUE TITLE
Is there any TextBox ui control available

### ISSUE THREAD

**Issue by kashishm** [andlabs/ui#172]
I saw `ui.NewEntry()` which is used for a single line of text info. But I couldn't find any multiline input control.

Could you please tell me if it is already implemented and how to use it?

**Comment by andlabs** [comment]
It is in libui, but I haven't synced that API to package ui yet, pending the next stable release of libui.

**Comment by emersion** [comment]
See #160

**Comment by kashishm** [comment]
Thanks for the updates. Can't wait until this is available!

**Comment by andlabs** [comment]
In that case, replaced with #277.

(More complex things like rich edit are a future goal.)
