### ISSUE TITLE
AreaKeyEvent: get the actual rune respecting the keyboard layout

### ISSUE THREAD

**Issue by mibk** [andlabs/ui#173]
Is there any way to get the actual rune respecting the keyboard layout?

**Comment by andlabs** [comment]
Not yet. This would lead to a more complex issue: proper text handling. See andlabs/libui#74.

I'm not sure if there's an advantage to having layout translation without full text input support. Is there?

**Comment by mibk** [comment]
Well, I was quite happy with defining my own `AreaHandler` capable of rendering text and handling key presses. Layout translation is the only thing that stays in my way to using this as a GUI frontend for my text editor I'm building. I already have termbox frontend for terminal. Basically all I need is just a window with `ui.Area` in it.

BTW this library is the best gui library for Go I've found so far. Thank you!

**Comment by mccolljr** [comment]
In line with @mibk, I find I like this UI library the best for Go. I am curious, though, if we're nearing a point where proper text support in a uiArea will be available? I took a look at andlabs/libui#74, seems that the last update was in August.

**Comment by andlabs** [comment]
I've started working on the issue now. Not sure how long it will take; need to prototype stuff.

**Comment by mccolljr** [comment]
@andlabs I'm not sure if it will be helpful to you at this point, but you might want to take a look at how JUCE does it.

[This is the file for Mac](https://github.com/julianstorer/JUCE/blob/680d75807accebce075850cbdd302ccf6c56e8f2/modules/juce_gui_basics/native/juce_mac_NSViewComponentPeer.mm)

[Most of the relevant files appear to reside in this folder (including the one above)](https://github.com/julianstorer/JUCE/tree/680d75807accebce075850cbdd302ccf6c56e8f2/modules/juce_gui_basics/native)

**Comment by andlabs** [comment]
Mac and GTK+ are mostly solved now. The problem is Windows, where the missing piece of the puzzle is how can I be told if a key press will become a character or not.

**Comment by mccolljr** [comment]
Wanted to touch base and see if you'd had any time to work on this. I've been away from GUI in Go for a while, but I've got some time to play around now.

**Comment by andlabs** [comment]
I worked on it by building a separate program for word processing, and in that I realized my APIs for drawing text are bad. I'm currently working on reworking those. After finishing that (which is about 70% done anyway), I'll make a point release (hopefully with tables too, depending on how long it takes), and then I'll start on text input.

**Comment by andlabs** [comment]
Merged with andlabs/libui#329.
