### ISSUE TITLE
Feature request: ability to call functions set with OnClicked/OnSelected/etc

### ISSUE THREAD

**Issue by tsudoko** [andlabs/ui#174]
E.g.

``` go
func Somefunc(b *ui.Button, arg1 string, arg2 int) func(*ui.Button) {
    return func(*ui.Button) {
        …
    }
}
…
    button := ui.NewButton("click")
    button.OnClicked(Somefunc(button, some, args))
…
    // different block, can't access "some" and "args"
    button.CallOnClicked()
…
```

Right now I can't find a good way to do this; there's the `onClicked` field, but I can't access it since it's not exported. I could store the function returned by `Somefunc(button, some, args)` in a different variable and call it when necessary, but why store it twice when it's in the struct already?

---

Actually, `OnClicked()` [is named like a getter, not a setter](https://golang.org/doc/effective_go.html#Getters), but I guess breaking the API right now is not an option.

**Comment by andlabs** [comment]
Merged with andlabs/libui#326.
