### ISSUE TITLE
Paste key on OS X does not work for Entry

### ISSUE THREAD

**Issue by norganna** [andlabs/ui#177]
In OS X, when you are focussed on an Entry, and press ⌘-V the clipboard text is not pasted.

I tried other combinations like ⌃-V and ⇧-Insert, which did not work either.

However when you right-click and select Paste, it is pasted. I did take a look around but could not find any reference to how to accomplish pasting by keypress.

**Comment by andlabs** [comment]
That has to do with menus and keyboard shortcuts; see andlabs/libui#152.

**Comment by norganna** [comment]
You know, I did a project search for the word "paste" and it turned up some results, but not that issue 152. And it clearly has the paste word in there. Sorry.

**Comment by norganna** [comment]
... which is because it's in the libui repository and not this one, doh.
