### ISSUE TITLE
Go get fails on linux_amd64

### ISSUE THREAD

**Issue by mixedCase** [andlabs/ui#180]
Get the following when trying to go get:

```
$ LANG=C go get -u github.com/andlabs/ui
# github.com/andlabs/ui
/usr/bin/ld: andlabs/ui/libui_linux_amd64.a(libui-combined.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

`LANG=C` merely used to have the errors in English.

**Comment by mixedCase** [comment]
Trying to run the example [here](https://github.com/andlabs/ui/wiki/Getting-Started) after the failed `go get` also returns the same error.

**Comment by andlabs** [comment]
What version of Go?

**Comment by mixedCase** [comment]
```
$ go version
go version go1.6.3 linux/amd64
```

**Comment by joeblew99** [comment]
how did you install teh gcc tools ?

what linux are you on ?

**Comment by andlabs** [comment]
The binaries might not be built with PIC. I'll need to see how to get cmake to do it, if I didn't already...

**Comment by mixedCase** [comment]
@joeblew99 Through my distro's package manager. I'm using Arch Linux, GCC is version 6.1.1.

**Comment by joeblew99** [comment]
Ok. I am on Ubuntu and used the package manager on Ubuntu.

I am wondering if I can help and land with the cross built.
Maybe the xgo github project would help ? I am only guessing about this though.

If others like me would compile everything I could also maybe help with the matching of the c code to the golang code.

**Comment by emersion** [comment]
xgo works for macOS, but not Windows (see https://github.com/karalabe/xgo/issues/55).

You need the latest mingw-w64 (5.0rc2) which hasn't yet been released.

**Comment by joeblew99** [comment]
https://packages.debian.org/search?keywords=mingw-w64

Debian experimental looks to have the mingw-w64 (5.0rc2). Maybe worth trying in a VM ?

**Comment by joeblew99** [comment]
Ok thanks Emerson.
Looks like I have to wait

**Comment by mixedCase** [comment]
@andlabs How did you build these `.a` files and from what?

**Comment by andlabs** [comment]
Simply with

```
cmake -DBUILD_SHARED_LIBS=OFF ..
make
```

on 16.04.

**Comment by mixedCase** [comment]
@andlabs I can confirm that it works if I add -fPIC to libui's compiler instructions in CMakeLists.txt. Could you recompile and upload?

**Comment by mixedCase** [comment]
Pinging @andlabs in case you missed the last comment.

**Comment by andlabs** [comment]
I'll look into it soon.

**Comment by txthinking** [comment]
Should I install mingw-w64 (5.0rc2) and set CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ before `go get github.com/andlabs/ui` ?

**Comment by andlabs** [comment]
Yes.

**Comment by txthinking** [comment]
On Archlinux. installed gtk3.

Go
```
$ go version
go version go1.7.3 linux/amd64
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tx/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build663071203=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```
install mingw-w64-crt-git-5.0.rc2.r114.g563731c-1
```
$ yaourt -S mingw-w64-crt-git
```
get ui
```
$ CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go get -v -u github.com/andlabs/ui
github.com/andlabs/ui (download)
github.com/andlabs/ui
# github.com/andlabs/ui
/usr/lib/gcc/x86_64-w64-mingw32/6.2.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -ldl
/usr/lib/gcc/x86_64-w64-mingw32/6.2.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgtk-3
/usr/lib/gcc/x86_64-w64-mingw32/6.2.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgdk-3
/usr/lib/gcc/x86_64-w64-mingw32/6.2.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lpangocairo-1.0
/usr/lib/gcc/x86_64-w64-mingw32/6.2.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lpango-1.0
/usr/lib/gcc/x86_64-w64-mingw32/6.2.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -latk-1.0
/usr/lib/gcc/x86_64-w64-mingw32/6.2.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lcairo-gobject
/usr/lib/gcc/x86_64-w64-mingw32/6.2.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lcairo
/usr/lib/gcc/x86_64-w64-mingw32/6.2.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgdk_pixbuf-2.0
/usr/lib/gcc/x86_64-w64-mingw32/6.2.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgio-2.0
/usr/lib/gcc/x86_64-w64-mingw32/6.2.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgobject-2.0
/usr/lib/gcc/x86_64-w64-mingw32/6.2.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lglib-2.0
collect2: error: ld returned 1 exit status
```

**Comment by andlabs** [comment]
You must also set `$GOOS`.

**Comment by txthinking** [comment]
@andlabs Thanks, it works with mingw-w64-crt-git. #155

**Comment by NickCao** [comment]
The same issue for me on Ubuntu GNOME 16.10. Not fixed yet.

**Comment by andlabs** [comment]
What version of MinGW-w64 does Ubuntu come with?

**Comment by NickCao** [comment]
I was just building for Linux, maybe MinGW is not required?

**Comment by andlabs** [comment]
Do you want to build Linux-native programs or Windows-native programs?

**Comment by NickCao** [comment]
Linux-native (Sorry for responding so late. I was traveling these days.)

**Comment by andlabs** [comment]
Then your `$GOOS` is not set properly. What does `go env` print?

**Comment by NickCao** [comment]
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nickcao/Projects/Go"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by andlabs** [comment]
Your environment is correct for a Linux build. I'm not sure why it's trying to build the Windows one...

**Comment by NickCao** [comment]
Maybe building it manually instead of using go get can fix that?

**Comment by mixedCase** [comment]
Closing this because I no longer have the original issue.
