### ISSUE TITLE
Request for example repo

### ISSUE THREAD

**Issue by joeblew99** [andlabs/ui#181]
I am having trouble getting going.
The possibilities look great but because the readme docs are old and the wiki old, it would be awesome if there was a repo with an example .

Does anyone have any example repo's ?

**Comment by duckbrain** [comment]
The GoDoc is pretty good for the package.

I found https://godoc.org/github.com/andlabs/ui very helpful in figuring it all out.

**Comment by cryptix** [comment]
I started porting the old [wakeup](https://github.com/andlabs/wakeup) example to the new api some weeks ago but I forgot to push it and make a PR. I'll do so once I have access to that machine.

More examples would be good though.. What is the todomvc equiv of a native gui?

**Comment by joeblew99** [comment]
@cryptix thanks.

Not sure what you mean by asking for the todomvc equiv of a native gui.
i know what the todomvc is.
are you asking what UI controls to use to make a todo app ?

**Comment by cryptix** [comment]
@joeblew99: no. more like: what general thing could one build that has enough features so that it's not too "hello world"-like obvious.

**Comment by joeblew99** [comment]
@cryptix I get you now.

I have started to build a best practice thing to show different patterns for how to use the library.
https://bitbucket.org/gedw99/md-desktopnative-x

Its very early days on it. I just started

It seems that the code out there in github land is very out of date because the API has changed.
i tried your code but its also on the old API.

**Comment by joeblew99** [comment]
am closing this. reopen if you need to.

**Comment by andlabs** [comment]
I will provide examples when the API is more complete and when I resume work on this.

**Comment by joeblew99** [comment]
ok thanks. Really appreciate.

I got the test code working. Its very nice to use.

**Comment by andlabs** [comment]
Please leave this open.

**Comment by joeblew99** [comment]
Ok cool

**Comment by andlabs** [comment]
Merged with andlabs/libui#317.
