### ISSUE TITLE
go get on windows failed

### ISSUE THREAD

**Issue by joeblew99** [andlabs/ui#182]
hey everyone,

````
go get github.com/andlabs/ui
# github.com/andlabs/ui
exec: "gcc": executable file not found in %PATH%

````
Not sure where to get this and install it. Sorry

Maybe update the readme too, so its easier for others ?

thanks..

**Comment by joeblew99** [comment]
here is what i did. Can this be added to the Readme for others ?

In order to use cgo on Windows, you'll also need to first install a gcc compiler (for instance, mingw-w64) and have gcc.exe (etc.) in your PATH environment variable before compiling with cgo will work.

1. Download the installer from here:
https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/

2. Run the installer
- Go get a coffee, as it takes maybe 10 minutes....

3. Check where it installed it, and put the gcc.exe in your path.
- on my win 10 machine, it put it in: C:\Program Files (x86)\mingw-w64\i686-6.2.0-posix-dwarf-rt_v5-rev0\mingw32\bin

4. Now you can go get github.com/andlabs/ui

**Comment by joeblew99** [comment]
hmmm..

after rebooting...

````
C:\Users\root\workspace\go\src\github.com\andlabs>go get github.com/andlabs/ui
# github.com/andlabs/ui
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

````

any ideas ?

**Comment by emersion** [comment]
You've installed GCC for 32 bit, you cannot compile 64 bit binaries. You can set `GOARCH=386` to compile 32 bit binaries, or install mingw-w64.

**Comment by joeblew99** [comment]
thanks
this looks like a nice way to bootstrap..
https://github.com/golang/winstrap

**Comment by joeblew99** [comment]
thanks.

i reinstalled now with the amd64 version of GCC.

**Comment by joeblew99** [comment]
all works thanks...
