### ISSUE TITLE
go get fails on Linux amd64 Kubuntu 16.04

### ISSUE THREAD

**Issue by norbertfuhs** [andlabs/ui#187]
When I tried to install it via go get  I got an c compiler error:

noby@Jupiter:~$ go get github.com/andlabs/ui
pkg-config --cflags gtk+-3.0
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
pkg-config: exit status 1

**Comment by andlabs** [comment]
You need to install `libgtk3.0-dev`.

**Comment by norbertfuhs** [comment]
Thanks works like a charm!
