### ISSUE TITLE
Linker warning

### ISSUE THREAD

**Issue by SirWindfield** [andlabs/ui#193]
`ld: warning: object file (/Users/Sven/golang/src/github.com/andlabs/ui/libui_darwin_amd64.a(libui-combined.o)) was built for newer OSX version (10.11) than being linked (10.8)`

This is quite an easy fix to do. Dunno if it breaks backwards compatibility.

**Comment by andlabs** [comment]
Yes it will; I already know about the issue anyway (https://github.com/andlabs/libui/issues/111)

**Comment by slava-vishnyakov** [comment]
Any chance for a fix or maybe a workaround? This is still happening on Sierra...

![image](https://cloud.githubusercontent.com/assets/817931/23455338/442c6e46-fe80-11e6-96a9-cceb72ac3960.png)

**Comment by andlabs** [comment]
This is not a fatal error, but I will say that andlabs/libui#308 will fix this. Closing in favor of that.
