### ISSUE TITLE
got get build issues

### ISSUE THREAD

**Issue by cbehopkins** [andlabs/ui#195]
Hi,
I'm trying to get this working under windows and I'm stuck with what looks like some path issues.
$ go get github.com/mattn/go-gtk/gtk
# github.com/mattn/go-pointer
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status
# github.com/mattn/go-gtk/pango
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status
# github.com/mattn/go-gtk/glib
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

I don't know enough about the go get process of interaction with gcc to debug this further. Has anyone any hints?
My only thought was that I had got the cygwin side of things wrong. (Sorry this is my first attempt at a GUI under windows. )

**Comment by andlabs** [comment]
Why are you getting github.com/mattn/go-gtk/gtk? This does not use that package.

**Comment by cbehopkins** [comment]
Because I am a moron and copy and pasted from the wrong text file.
Sorry
