### ISSUE TITLE
Api for NewPasswordEntry missing?

### ISSUE THREAD

**Issue by qiukeren** [andlabs/ui#201]
Thanks for andlabs/ui, but I find that if there is anything missiong:

```
password := ui.NewPasswordEntry()
```
# command-line-arguments

./ui.go:24: undefined: ui.NewPasswordEntry

**Comment by emersion** [comment]
Not yet implemented, https://github.com/andlabs/ui/pull/169 adds it.

**Comment by andlabs** [comment]
Replaced with #277.
