### ISSUE TITLE
Watching for Enter key in my Entry box. 

### ISSUE THREAD

**Issue by pratapsu** [andlabs/ui#205]
Hi:

I need to realize when the user presses the Enter key in a Entry box. There is no interface for this at present, it appears. 

I'm able to watch all changes to the text in the Entry box using the OnChanged() interface, but that is insufficient for my needs, as it seems to swallow the Enter key entirely. 

Is there a way to do this today, am I missing something? If not, I'm happy to help with implementing this. 

Pratap

**Comment by duckbrain** [comment]
Related: #43 (this and other events), #66 (enter on the window), and andlabs/libui#1 (this in libui)

**Comment by andlabs** [comment]
Merged with andlabs/libui#309.
