### ISSUE TITLE
How to remove that black window behind?

### ISSUE THREAD

**Issue by StevenZack** [andlabs/ui#209]
OS: windows 7  32 bit 
go version : go1.7.4.windows-386
mingw version : mingw530_32

When I run the .exe file that I generated  using `go build` , it  always had a black cmd window behind it 
although everything went fine , I still want to know how to get rid of it

**Comment by andlabs** [comment]
There are already a number of issues open for this; look around.

**Comment by StevenZack** [comment]
Found it  #90
