### ISSUE TITLE
How to update UI in multible thread

### ISSUE THREAD

**Issue by StevenZack** [andlabs/ui#210]
I came out with this question when i was trying to write a GUI of a go web server . 
I want to dynamically  update my ui in other thread.

In Qt , i can do  this by using Signal and Slot

**Comment by andlabs** [comment]
The answer is use `ui.QueueMain()`.

**Comment by StevenZack** [comment]
Can you give an simple example ?Fogive me. I'm a freshman of programing , I really like this library

**Comment by emersion** [comment]
From any goroutine, you can do:
```go
ui.QueueMain(func () {
    // Update the UI here
})
```

**Comment by StevenZack** [comment]
awesome! Thanks man
