### ISSUE TITLE
how to add widget to area?

### ISSUE THREAD

**Issue by jmesyan** [andlabs/ui#213]
andlabs ,how to add a widget to a scrolling area ,if area can take some widget like label ,button. i don't know how to use,please give some example,thanks!

**Comment by andlabs** [comment]
That functionality isn't present yet, nor am I sure if or when it will happen...

**Comment by James-Yan** [comment]
I see, thank you

**Comment by andlabs** [comment]
Merged with andlabs/libui#329.
