### ISSUE TITLE
how to get the time of DateTimePicker

### ISSUE THREAD

**Issue by jmesyan** [andlabs/ui#214]
andlabs,I want to use the DateTimePicker,but find there is no method to get the time,could you help me?

**Comment by andlabs** [comment]
I have not written that yet; sorry. I still need to figure out how I'm going to expose the time information.

**Comment by James-Yan** [comment]
if i know how your write,i guess i can help you ,but i am not good at c and libui.now ,i find a way use your ui as mvc mode,but the widget need a lot of perfect

**Comment by andlabs** [comment]
Merged with andlabs/libui#297. Go API will come later. Closing for now.

**Comment by jmesyan** [comment]
cool
