### ISSUE TITLE
How do you create a Textarea?

### ISSUE THREAD

**Issue by Xeoncross** [andlabs/ui#215]
It's easy enough to create a [text input](https://github.com/andlabs/ui/blob/master/entry.go#L34) (single line) but how can you create a textarea (supports multiple lines)?

		myInput := ui.NewEntry()
		myTextarea := ???

**Comment by andlabs** [comment]
There is a plain text multiline entry in libui; it will be added to package ui in the next binary release. Rich text will have to wait a bit longer, but custom text-handling areas are in the works.

**Comment by Xeoncross** [comment]
You can save some work by just pulling https://github.com/ProtonMail/ui since they seem to have already typed it out for you.

**Comment by nnvn** [comment]
Came here to ask the same question.

**Comment by centifocus** [comment]
the same question for me.

**Comment by andlabs** [comment]
Replaced with #277.

(More advanced things, like rich edit, will come in the future.)
