### ISSUE TITLE
Window is black when opened from another window (OSX)

### ISSUE THREAD

**Issue by Xeoncross** [andlabs/ui#218]
I am opening a confirm window from a button inside another window. However, the new window is completely black and the windows stop responding telling me that the libui must be waiting for something. 

What is the correct way to open a window on a button click?

```
func confirmWindow(title, msg string) bool {
	w := ui.NewWindow("Confirm", 300, 100, true)
	w.SetMargined(true)
	if title != "" {
		w.SetTitle(title)
	}

	c := make(chan bool)

	confirm := ui.NewButton("Ok")
	confirm.OnClicked(func(b *ui.Button) {
		c <- true
	})

	deny := ui.NewButton("Cancel")
	deny.OnClicked(func(b *ui.Button) {
		c <- false
	})

	box := ui.NewHorizontalBox()
	box.SetPadded(true)
	box.Append(confirm, true)
	box.Append(deny, true)

	wrapper := ui.NewVerticalBox()
	wrapper.SetPadded(true)
	wrapper.Append(ui.NewLabel(msg), true)
	wrapper.Append(box, true)
	w.SetChild(wrapper)
	w.Show()

	return <-c
}
```

Worth noting that a file selector window opens just fine:

		fileButton.OnClicked(func(b *ui.Button) {
			x := ui.OpenFile(ui.NewWindow("Choose a File", 500, 500, true))
			fmt.Println("User chose a file:", x)
		})

**Comment by Xeoncross** [comment]
Solved. I can't hang out inside the `OnChange()` function. I need to exit the function in order for libui to draw the new window and the return <-c was waiting for the response from the window that wasn't drawn yet.

**Comment by andlabs** [comment]
The file selector window works fine because it doesn't return until you select a file, and while it's open the system is processing events which allows the rest of the app to draw properly.

**Comment by Xeoncross** [comment]
I just ended up using a callback instead of trying to select on goroutines. Something like this:

```
func callbackWindow(title, msg string, callback func()) {
	w := ui.NewWindow("Confirm", 300, 100, true)
	w.SetMargined(true)
	if title != "" {
		w.SetTitle(title)
	}

	confirm := ui.NewButton("Click me")
	confirm.OnClicked(func(b *ui.Button) {
		w.Destroy()
		callback()
	})

	wrapper := ui.NewVerticalBox()
	wrapper.SetPadded(true)
	wrapper.Append(ui.NewLabel(msg), true)
	wrapper.Append(confirm, false)
	w.SetChild(wrapper)
	w.Show()

}
```
