### ISSUE TITLE
TreeView & TableView

### ISSUE THREAD

**Issue by dubcanada** [andlabs/ui#22]
I'm currently using QT for a very basic tree view and table view application, I'd love to port it over to this library.

Is there any roadmap of when treeview support may appear?

**Comment by andlabs** [comment]
I'd probably write my own Tree for Windows instead, but I'll probably use a model-based setup like GTK+ does for that (and it'd probably wait for XP support to be dropped because there's no way I'm making that accessible with MSAA and I still need to evaluate UI Automation).

**Comment by bcampbell** [comment]
see also #125

**Comment by andlabs** [comment]
Yes, pretty much everything I said in 2015 is effectively outdated now.

**Comment by andlabs** [comment]
Replaced with andlabs/libui#310.
