### ISSUE TITLE
Issue building on W64

### ISSUE THREAD

**Issue by Arie-vw** [andlabs/ui#221]
go run main.go

# github.com/andlabs/ui
e:/src/go/src/github.com/andlabs/ui/libui_windows_amd64.a(stddialogs.cpp.obj): In function `msgbox':
E:/github.com/andlabs/libui/windows/stddialogs.cpp:113: undefined reference to `__imp_TaskDialog'
collect2.exe: error: ld returned 1 exit status

**Comment by andlabs** [comment]
You will find this issue reported countless times here. Upgrade to MinGW-w64 5.0.
