### ISSUE TITLE
Error message when trying to run tutorial code

### ISSUE THREAD

**Issue by carlca** [andlabs/ui#224]
Go 1.7.4 Windows 10 Pro 64 bit Insider Preview build 15014 
JetBrains Gogland 163.12024.27
Git Bash

Grabbed the andlabs/ui code, everything seemed to install ok. When I tried to run the example code in the wiki, I received the following error message:

```
$ go run main.go
# github.com/andlabs/ui
c:/gocode/src/github.com/andlabs/ui/libui_windows_amd64.a(stddialogs.cpp.obj): In function `msgbox':
E:/github.com/andlabs/libui/windows/stddialogs.cpp:113: undefined reference to `__imp_TaskDialog'
collect2.exe: error: ld returned 1 exit status
```

Any idea what's up?
Thanks,
Carl
,

**Comment by andlabs** [comment]
Duplicate of countless other issues; upgrade to MinGW-w64 5.0.
