### ISSUE TITLE
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in on go get

### ISSUE THREAD

**Issue by comaldave** [andlabs/ui#227]
This is the error I receive when I go get ...
    PS > go get github.com/andlabs/ui
    # github.com/andlabs/ui
    cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

go version go1.7.5 windows/amd64
g++.exe (GCC) 5.3.0

**Comment by andlabs** [comment]
How did you install g++?

**Comment by comaldave** [comment]
I went to http://www.mingw.org/

selected downloads and Looking for the latest version? *Download
mingw-get-setup.exe (86.5 kB)
<https://sourceforge.net/projects/mingw/files/latest/download?source=files>*



*I included c:\MinGW\bin on my system pathI deleted an old copy of mingw
that had been previously installed in another directory.*

**Comment by andlabs** [comment]
That's the ancient MinGW. You want MinGW-w64.

**Comment by comaldave** [comment]
Thank you. I am 63 years old so tend to end up with the most ancient
version.

On Thu, Feb 16, 2017 at 12:00 PM, Pietro Gagliardi <notifications@github.com

**Comment by comaldave** [comment]
g++.exe (x86_64-posix-seh-rev1, Built by MinGW-W64 project) 6.3.0

go get runs with no errors. Thank you.
