### ISSUE TITLE
Example for multi line

### ISSUE THREAD

**Issue by rogierlommers** [andlabs/ui#233]
I'm having a hard time finding examples for multi line text. So ideally I would have one element, a textarea, where I can send text to (from other go routines, packages, etc). These pieces of text should be added to the textarea. Also some auto-scrolling? :) Would love an example like this, because I can't figure it out myself.

**Comment by centifocus** [comment]
https://github.com/ProtonMail/ui/blob/patches/multilineentry.go

**Comment by andlabs** [comment]
Merged with andlabs/libui#317.
