### ISSUE TITLE
Color text

### ISSUE THREAD

**Issue by trevordixon** [andlabs/ui#234]
I'm drawing text like this:
```
tl := ui.NewTextLayout(str, font, -1)
dp.Context.Text(x, y, tl)
```
How can I set the color used to draw the text? I see `uiDrawTextLayoutSetColor ` in https://github.com/andlabs/libui/blob/1369f53027a07e0b93f0d61644a083d396bd3e88/unix/drawtext.c#L276-L293. Is that exposed anywhere on the Go side?

**Comment by andlabs** [comment]
No, and I'm in the process of replacing that API with something better anyway (see libui branch utflib-and-attrstr or whatever it's called). Once that is done I can port the new API to Go.

**Comment by andlabs** [comment]
libui now has a new attributed string API that will let you do this. It is not yet in package ui; there will be a separate master issue to monitor when package ui is synced. Until then, closing.
