### ISSUE TITLE
The current version ships with an obsolete version of libui (under OS X)

### ISSUE THREAD

**Issue by serge-hulne** [andlabs/ui#236]
Hi, 

The current version ships with an obsolete version of libui (under OS X).

How could I provide my own version of libui ?

Is there a version of the code (or a version of the Makefile) which looks for an installation of libui on the system rather than installing a specific (possibly obsolete) one.

Thanks.

**Comment by andlabs** [comment]
This is intentional; package ui only ships with tagged stable versions of libui, and there hasn't been one since then.

You can substitute `libui_darwin_amd64.a` with one built from source using `cmake -DBUILD_SHARED_LIBS=OFF`. Do note that the API might have changed.

**Comment by andlabs** [comment]
Replaced with #277.
