### ISSUE TITLE
GUI exists immediately after "enter" or "esc" is pressed

### ISSUE THREAD

**Issue by cfbao** [andlabs/ui#239]
Microsoft Windows [Version 6.1.7601]
go version go1.8.3 windows/amd64
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 7.1.0
ui installed with go get

I tested ui with the sample code in the Getting Started Wiki page, and noticed that the program exists IMMEDIATELY* after I pressed enter or esc. This happens with everything I tried with ui, all the way down to an empty window.
If the program is not built with window mode (without "-ldflags -H=windowsgui"), the errorlevel from such unexpected exit is -2147483645 as reported from cmd. Clicking on the red cross exit button results in normal exit with errorlevel 0.

*Immediately: not even deferred functions are executed, so it's not a go panic. might be something on libui side? Is this something related to how ui is built/installed?

**Comment by andlabs** [comment]
There's a PR In libui to fix it. I need to merge it.

**Comment by xoviat** [comment]
Yeah this is actually one of the issues I've been experiencing. 

```
Exception 0x80000003 0x0 0xffffd98d9c8fe700 0x7fffa59fa952
PC=0x7fffa59fa952
signal arrived during external code execution

github.com/andlabs/ui._Cfunc_uiMain()
        github.com/andlabs/ui/_obj/_cgo_gotypes.go:1732 +0x48
github.com/andlabs/ui.start(0xc042042060, 0x4887a8)
        C:/Users/User/go/src/github.com/andlabs/ui/main.go:56 +0x1ab
created by github.com/andlabs/ui.Main
        C:/Users/User/go/src/github.com/andlabs/ui/main.go:36 +0x72

goroutine 1 [chan receive]:
github.com/andlabs/ui.Main(0x4887a8, 0xc042026000, 0xc042026000)
        C:/Users/User/go/src/github.com/andlabs/ui/main.go:37 +0xa8
main.main()
        C:/Users/User/workspace/test/main.go:25 +0x34

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:2197 +0x1
rax     0x7fffa8386bc0
rbx     0x1
rcx     0x5ea540
rdi     0x80000010
rsi     0x0
rbp     0xb3f8b0
rsp     0xb3f858
r8      0x1250fc0
r9      0x8000
r10     0x141b150
r11     0x141b320
r12     0x60a12
r13     0x111
r14     0x0
r15     0x0
rip     0x7fffa59fa952
rflags  0x206
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by PaluMacil** [comment]
I'm holding off on using the lib till this is fixed. I know you've mentioned before not having a ton on experience with Git, and I do some training on Git, so if you want some support on any versioning strategies, cherry-picking individual hot fixes to other branches, or anything else, I am able to assist. 👍

**Comment by StevenZack** [comment]
@andlabs can you fix this bug? I've been waiting for so long

**Comment by andlabs** [comment]
Fixed (hopefully).

**Comment by PaluMacil** [comment]
Works for Go 1.10 on Win 10! Thanks a lot! 👍 I'm excited for this.

**Comment by andlabs** [comment]
OK!
