### ISSUE TITLE
How to hide console under Mac OS X?

### ISSUE THREAD

**Issue by rafw** [andlabs/ui#240]
Under Windows, `go build -ldflags -H=windowsgui main.go` could do this. But there is also console under OS X, how to hide it?

**Comment by andlabs** [comment]
Are you running from a console? OS X doesn't have Windows-like console behavior...

**Comment by rafw** [comment]
No, I double click the binary file from path finder.

**Comment by rafw** [comment]
<img width="582" alt="3eb15c2b-f480-4288-aabf-e9e9f97639d4" src="https://user-images.githubusercontent.com/4507840/28195154-1effded6-687b-11e7-9ba8-036c5c15d677.png">

**Comment by andlabs** [comment]
Ah, so OS X does open a terminal for Terminal-based apps from the Finder. Try running from a .app bundle.

**Comment by rafw** [comment]
Yes, if I rename the binary file to *.app, there is no terminal after running again.

**Comment by SudoUserReal** [comment]
> Yes, if I rename the binary file to *.app, there is no terminal after running again.

Love from China.
