### ISSUE TITLE
How can open a dialog for select folder? (like OpenFile)

### ISSUE THREAD

**Issue by talut** [andlabs/ui#242]
Hi! Thank for this library. It's working so well. But I need a info about selecting a folder. How can select a folder like ui.OpenFile?

**Comment by andlabs** [comment]
I haven't implemented that yet. I will when I figure out some technical issues with dialogs...

**Comment by taluttasgiran** [comment]
@andlabs Thanks for info. 👍

**Comment by mingxi** [comment]
@andlabs I can't select a .zip file using ui.OpenFile.(on Windows)

**Comment by andlabs** [comment]
@mingxi can you report that as a different bug? That's definitely a problem...

**Comment by mingxi** [comment]
@andlabs Reported it in #243, thanks for your reply.

**Comment by andlabs** [comment]
Replaced with andlabs/libui#314.
