### ISSUE TITLE
Any way to customise colour or style?

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [andlabs/ui#246]
The standard appearance of windows, buttons etc, isn't very pretty to look at. Can i combine this with some other library to change colours, looks, or anything really? Also, Can I add images in the window somehow?

If there's a built in way to do this then my bad. I didn't find it

**Comment by andlabs** [comment]
Which OS are you looking at? I don't have any color options in libui, but depending on the OS you could change the system theme...

Image controls will be added after table controls. (They will not be used to provide window backgrounds.)

**Comment by AlmightyFloppyFish** [comment]
Using Ubuntu however, I'd preferably want to make it look the same on Windows as well.

**Comment by rawsh** [comment]
@AlmightyFloppyFish I would recommend going with qt if you want everything to look the same. There are a few qt bindings for go. Also, everything looking the same isn't really the point of libui - (I think) it's more about using the native library.

**Comment by andlabs** [comment]
Merged with andlabs/libui#313.
