### ISSUE TITLE
linux compile issue

### ISSUE THREAD

**Issue by rawsh** [andlabs/ui#248]
Using the documentation example, a (fedora) compile for windows fails:

```
env CC=x86_64-w64-mingw32-gcc CCX=x86_64-w64-mingw32-g++ GOOS=windows GOARCH=amd64 go build -v

# gui
./gui.go:8: undefined: ui.Main
./gui.go:9: undefined: ui.NewEntry
./gui.go:10: undefined: ui.NewButton
./gui.go:11: undefined: ui.NewLabel
./gui.go:12: undefined: ui.NewVerticalBox
./gui.go:13: undefined: ui.NewLabel
./gui.go:17: undefined: ui.NewWindow
./gui.go:19: undefined: ui.Button
./gui.go:22: undefined: ui.Window
./gui.go:23: undefined: ui.Quit
./gui.go:23: too many errors
```
A normal build works fine.

**Comment by andlabs** [comment]
Try also adding `CGO_ENABLED=1`.

**Comment by rawsh** [comment]
@andlabs huh, that fixed it. It didn't before.

**Comment by andlabs** [comment]
Right, you need to explicitly enable cgo when cross-compiling. Good luck!

**Comment by andlabs** [comment]
You also need to set `$CC` and `$CXX` to point to the appropriate C and C++ compilers. Other than that, I wouldn't know unless you enabled verbose or debug output on gox, because I don't know what gox is doing.
