### ISSUE TITLE
Multiline text input

### ISSUE THREAD

**Issue by rawsh** [andlabs/ui#249]
I see that it's done in a few issues, how can it be set up? I would be eternally grateful for an example. Also, how can I add some padding (the text in the example you have is right on the edge of the window). SetPadding(true) does not change anything for me.

Thanks,
Robert

**Comment by andlabs** [comment]
Margins around the window are done with `SetMargined(true)`.

I haven't put multiline text fields in the Go bindings yet, sorry. They'll go in on the next binary release.

**Comment by rawsh** [comment]
Ok, cool. I found multiline text in another repo so I will use that for now.
