### ISSUE TITLE
menu

### ISSUE THREAD

**Issue by rawsh** [andlabs/ui#250]
I tried to add a menu, but it fails...

```
./gui.go:19: undefined: ui.NewMenu
./gui.go:20: undefined: ui.MenuAppendItem
./gui.go:22: undefined: ui.MenuItemOnClicked
./gui.go:22: undefined: openClicked
```

Is this implemented?

**Comment by andlabs** [comment]
Not in package ui yet, because I'm not happy with the API. I'm still thinking about a better menu API, but it's not going into libui until after the next binary release.

**Comment by rawsh** [comment]
Ok, thanks for your reply.
