### ISSUE TITLE
"You must include this library in your binary distributions."

### ISSUE THREAD

**Issue by rawsh** [andlabs/ui#252]
> It is based on my libui, a simple cross-platform library that does the same thing, but written in C. You must include this library in your binary distributions.

Does this mean that libui needs to be included when I build? (How can I do that?) Also, what would you recommend for building for darwin - is there a way to do it from linux?

**Comment by andlabs** [comment]
The README is outdated; libui is now linked statically.

**Comment by rawsh** [comment]
Ok, cool.
