### ISSUE TITLE
Fedroa 27 / linux and gtk+-3.0 error.

### ISSUE THREAD

**Issue by catafest** [andlabs/ui#255]
This not working with Fedora 27 ( linux ) .
The reason is:
`Package 'gtk+-3.0', required by 'virtual:world'`
I this can be done by implementation of go package under Fedora distro with gtk , but also you need to know that. because can be required also from many linux distro.

**Comment by andlabs** [comment]
That error message is incomplete, and does not come from anything related to package ui... Can you print the full console log, including command line?

**Comment by Vigneshr6** [comment]
I got the same error in CentOS 7.
```
go get github.com/andlabs/ui
# pkg-config --cflags gtk+-3.0
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
pkg-config: exit status 1
```

**Comment by andlabs** [comment]
@Vigneshr6 that error means you did not install the GTK+ devel files. I don't know what `dnl` package this is, sorry.

**Comment by Vigneshr6** [comment]
Thanks @andlabs .
After installing gtk3-devel package,I did not face any problem.

**Comment by seagle0128** [comment]
Should update README.

**Comment by andlabs** [comment]
Added correct `dnf` invocation to README. Not fully satisfied with this instruction right now, but it'll do for now. Closing in the meantime (I added requisite TODOs).
