### ISSUE TITLE
Example for Areas?

### ISSUE THREAD

**Issue by salacryl** [andlabs/ui#257]
hi, can anyone provide a working example for areas?
I created a type struct and implemented the interface, but: Draw is never called.

Greetings Björn

**Comment by andlabs** [comment]
Can you show your code? It might help figure out what you're doing wrong.

**Comment by salacryl** [comment]
Hey 
`package main

import (
	"fmt"

	"github.com/andlabs/ui"
)

type areaHandlerDraw struct {
	a  *ui.Area
	dp *ui.AreaDrawParams
}

func (t areaHandlerDraw) Draw(a *ui.Area, dp *ui.AreaDrawParams) {
	panic("Blubb")
	fmt.Printf("%+v\n", dp)
	return
}

func (t areaHandlerDraw) MouseEvent(a *ui.Area, me *ui.AreaMouseEvent) {
	return
}

func (t areaHandlerDraw) MouseCrossed(a *ui.Area, left bool) {
	return
}

func (t areaHandlerDraw) DragBroken(a *ui.Area) {
	return
}

func (t areaHandlerDraw) KeyEvent(a *ui.Area, ke *ui.AreaKeyEvent) (handled bool) {
	return
}

func main() {

	err := ui.Main(func() {
		
		a := areaHandlerDraw{nil,nil}

		logo := ui.NewArea(a)
		
		logo.Show()
		button := ui.NewButton("OK")
		greeting := ui.NewLabel("")
		box := ui.NewVerticalBox()
		box.Append(ui.NewLabel("Enter your name:"), false)
		box.Append(logo, false)
		box.Append(button, false)
		box.Append(greeting, false)
		window := ui.NewWindow("Hello", 200, 100, false)
		window.SetChild(box)
		button.OnClicked(func(*ui.Button) {
			//greeting.SetText("Hello, " + name.Text() + "!")
		})
		window.OnClosing(func(*ui.Window) bool {
			ui.Quit()
			return true
		})
		window.Show()
	})
	if err != nil {
		panic(err)
	}
}
`
I also tried to pass an AreaDrawParams, but it doesn't matter. I thought the two params for the struct  must be filled by the NewArea function (like WinAPI often do it).

I don't know. I just tried this once.

**Comment by andlabs** [comment]
Oh, with the current API you're asking for an Area which is automatically sized, and by passing `false` to `box.Append()` the result will be an Area with zero size. You can make it `true`, but IDK if that is an adequate solution to what you want. I need to add a `SetMinSize()` method sometime.

**Comment by salacryl** [comment]
Great! With the true parameter the panic dropped. I thought of it, but didn't tried it!
Ok, I'll test somethings with ui and fork it, maybe I'll can help you, to get something off the list for you :)

**Comment by andlabs** [comment]
Merged with andlabs/libui#317.
