### ISSUE TITLE
how to select a folder

### ISSUE THREAD

**Issue by bean-du** [andlabs/ui#260]
I can't select a folder use `ui.OPenFile`, please help me
this is my code
```go
func initUI()  {
	b := ui.NewButton("选择文件")
    w := ui.NewWindow("选择文件",300,300,false)
	b.OnClicked(func(button *ui.Button) {
		s := ui.OpenFile(w)
		fmt.Println(s)
	})
	window := ui.NewWindow("Hello", 200, 100, false)
	window.SetMargined(true)
	window.SetChild(b)
	window.Show()
}

func main() {
	err := ui.Main(initUI)
	if err != nil {
		panic(err)
	}
}
```

**Comment by andlabs** [comment]
I have not added that functionality yet; it is planned once I figure out the best way to implement dialog boxes due to OS-specific quirks that even the current implementation falls subject to.

**Comment by andlabs** [comment]
Replaced with andlabs/libui#314.

**Comment by zhaoguotao** [comment]
OpenFolder added?
