### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by binary132** [andlabs/ui#262]
If this project is unmaintained, please mark it as such in the README so that people will be aware.

**Comment by andlabs** [comment]
IT IS NOT UNMAINTAINED

**Comment by binary132** [comment]
Last commit on master was 2 years ago?

**Comment by andlabs** [comment]
Most development is now on andlabs/libui instead. andlabs/ui gets updated whenever a packaged release of the former is made, which hasn't been done in a while.
