### ISSUE TITLE
color window?

### ISSUE THREAD

**Issue by monouser7dig** [andlabs/ui#266]
Is there an way to have something styled like [this](https://marta.yanex.org)?
~~Is there any API documentation besides the examples?~~ (go newbi) (found it https://godoc.org/github.com/andlabs/ui)

![](https://marta.yanex.org/data/images/kon.png)

thanks (at least it still compiles and opens a window)

what I want to do specifically is:
- change look / color
- handle drag n drop events
- handle keyboard events like `cmd+q`
- draw images

**Comment by andlabs** [comment]
Merged with andlabs/libui#313.

**Comment by monouser7dig** [comment]
should I open new issues on libui for
- handle drag n drop events
- handle keyboard events like cmd+q

?

thanks for the update

**Comment by andlabs** [comment]
No; those are also being considered. Thanks, though!

(Ideally after all of this, andlabs/ui's issue tracker will only contain issues specific to andlabs/ui, such as the NSUndoManager issues.)

**Comment by monouser7dig** [comment]
ok I'll just wait and see, good to see things moving again, the lib was nice to start but I got kind of stuck but would like to come back!

So I appreciate your effort! 🎉
