### ISSUE TITLE
Set label width? Wrap text?

### ISSUE THREAD

**Issue by Chownie** [andlabs/ui#267]
Is there no way to limit the width of onscreen text/wrap longer text, or am I missing a different widget to perform this?

I see TextLayout but that forces a move from a widget/control scheme into drawing onto a screen at which point I might as well just jump and use SDL instead

**Comment by andlabs** [comment]
Yes, uiLabel is rather primitive right now. I could add those at some point. In the meantime, a multiline uiMultilineEntry will do (though I forget if that's in package ui yet).

**Comment by Chownie** [comment]
Is there a timeline for updates to ui? I know it updates in tandem with libui but there's a lot of fragmentation on whether people are using andlabs/ui, protonmail/ui or bcampbell/ui at the moment.

**Comment by andlabs** [comment]
When my employer grants me copyright clearance, I will apply a patch on libui for a common bug that people report, make a new binary release, and sync the APIs for the resultant Alpha 3.5 release. I can't tell you when that first part is; sorry. I expect the soonest to be sometime in the middle of the month (assuming they grant the request this time).

**Comment by Chownie** [comment]
Fair enough! I hadn't realized that you were limited for releases by your employer, I completely understand.

**Comment by andlabs** [comment]
It's a new development (I only started 2 months ago). I admit I was either lazy or unmotivated (or too focused on one git branch) prior to that, but I am back in the game now.

**Comment by andlabs** [comment]
Replaced with andlabs/libui#309.
