### ISSUE TITLE
Go security release (1.8.7 / 1.9.4) breaks package compilation

### ISSUE THREAD

**Issue by rasky** [andlabs/ui#268]
Description of the Go fix that breaks compilation: http://golang.org/issue/23672

`LDFLAGS` now has a whitelist in place for options it accepts, and it doesn't accept bare filenames. This breaks compilation of `ui`.

https://github.com/andlabs/ui/blob/2dde2a79e7020f065d94d9bc17e0191bf18a5bff/link_linux_386.go#L8

There should probably be a `-l` added in front of the base library name, and a `-L` for the directory.

**Comment by andlabs** [comment]
I cannot make any fixes currently. What would the equivalent fix on Windows be (note that it needs to link to a .res file as well)?

**Comment by andlabs** [comment]
Fixed by Go itself. See also https://github.com/golang/go/issues/23749
