### ISSUE TITLE
mac osx 10.13.3 build error

### ISSUE THREAD

**Issue by cjmxp** [andlabs/ui#271]
mac osx 10.13.3 build error 
invalid flag in #cgo LDFLAGS: -mmacosx-version-min=10.8

**Comment by andlabs** [comment]
Duplicate of https://github.com/golang/go/issues/23749. Upgrade to Go 1.10 for now.

**Comment by cjmxp** [comment]
@andlabs go version go1.10 darwin/amd64

**Comment by andlabs** [comment]
Will investigate later.

**Comment by andlabs** [comment]
Okay, the Go team is aware and will fix it soon.
