### ISSUE TITLE
Can't compile on mac

### ISSUE THREAD

**Issue by Tricky1975** [andlabs/ui#273]
~~~shellscript
go build github.com/andlabs/ui
~~~
results into:
~~~
go build github.com/andlabs/ui: invalid flag in #cgo LDFLAGS: -mmacosx-version-min=10.8
~~~

MacOS version: 10.12.6 (Sierra)
Go version: go version go1.10 darwin/amd64

It used to work in older Go versions

**Comment by andlabs** [comment]
The Go team is working on fixing this.

**Comment by Tricky1975** [comment]
Ah so this is an issue in Go itself?

**Comment by andlabs** [comment]
Yes, it's the result of a security fix. Try setting `CGO_LDFLAGS_ALLOWED`.

**Comment by Tricky1975** [comment]
Thank you, I will investigate this ;)
