### ISSUE TITLE
go get on osx 10.13.3

### ISSUE THREAD

**Issue by CGuidi** [andlabs/ui#274]
go version :  
- go1.10 darwin/amd64  

gcc version : 
  - Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-    dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer  /SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
  Apple LLVM version 9.0.0 (clang-900.0.39.2)
  Target: x86_64-apple-darwin17.4.0  
  Thread model: posix
  InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

When calling `go get "github.com/andlabs/ui"` I got `go build github.com/andlabs/ui: invalid flag in #cgo LDFLAGS: -mmacosx-version-min=10.8`

**Comment by andlabs** [comment]
Duplicate of a handful of other issues already. The Go team will be fixing this; it is related to a security fix in Go itself. Use the `CGO_LDFLAGS_ALLOW` environment variable in the meantime.

**Comment by CGuidi** [comment]
Thank, I could get the package 🙂
