### ISSUE TITLE
MacOS: Cmd+Q doesn't work for quit and the quit menu item is grayed out?

### ISSUE THREAD

**Issue by philiplb** [andlabs/ui#275]
Hi,
I can't quit the hello world application via Cmd+Q and the quit menu item is greyed out. How can I activate this feature?

**Comment by andlabs** [comment]
You need to add a Quit item to the menu bar. I haven't brought the menu API to Go yet because I'm not happy with it...

**Comment by philiplb** [comment]
Thx for the quick answer.
Ok, how do I use the menu bar?

**Comment by andlabs** [comment]
See #277 and andlabs/libui#321. Closing for now.
