### ISSUE TITLE
Tracking issue for package ui not having everything in libui, Alpha 4 edition

### ISSUE THREAD

**Issue by andlabs** [andlabs/ui#277]
Package ui's guts are now in a separate repository, github.com/andlabs/libui, which undergoes active development and API changes. To keep things sane, package ui now only syncs up to libui on a point release of the latter.

There have been a few in the Alpha 3 range, but I have not yet migrated existing APIs to package ui, both because I know I'm getting rid of them soon and because of other bugs in libui and time constraints (including, but not limited to, being unable to build a linux/386 version of Alpha 3.5). Alpha 4 will stabilize everything again.

All the build and multithreading issues are a nightmare as well. I want to square those away, and those will be part of Alpha 4.

So, package ui will sync with libui on Alpha 4. You can use this issue to monitor when that happens.

Other notes:

- Menus are blocked by andlabs/libui#321
- Tables are blocked by them not being merged back in yet

**Comment by andlabs** [comment]
Obsolete; all of the planned stuff for Alpha 4 has now been added

**Comment by MatGarreau** [comment]
Hi @andlabs , you said that all planned stuff has been done, but I'm still searching how to set element alignement inside hbox or vbox. Did this objects provides alignement functions ? Is there an easy way to centered text inside an GUI ? Thanks by advance for your response :-)

**Comment by andlabs** [comment]
No, not yet. You CAN use a uiGrid with a single row or column, though.

**Comment by MatGarreau** [comment]
Thanks for your answer @andlabs . Do you have this new feature in your todo list ? ;-)

**Comment by stupidjohn** [comment]
@andlabs hello, i saw the file picker issue been closed, but still not usable yet ?
