### ISSUE TITLE
MinGW-w64 Issues

### ISSUE THREAD

**Issue by teamrehab** [andlabs/ui#288]
Can someone please link me to the exact version of MinGW-w64 I should be using in Win10 64bit?

No matter what I try, I get the same errors that people here get when using the wrong version.

It says I'm using x86_64-7.3.0-posix-seh-rt-v5-rev0

Thanks!

**Comment by teamrehab** [comment]
Closing this. my paths were accidentally set to winbuilder.

**Comment by andlabs** [comment]
Ah, all right. Good luck!
