### ISSUE TITLE
error on "go get -u github.com/andlabs/ui"

### ISSUE THREAD

**Issue by jkmpariab** [andlabs/ui#296]
# github.com/andlabs/ui
/usr/bin/x86_64-linux-gnu-ld: go/src/github.com/andlabs/ui/libui_linux_amd64.a(libui-combined.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
-----------------------------------------------------------------------------------------------------
system specs: ubuntu 18.04 amd64 - go version 1.10.2

**Comment by andlabs** [comment]
Duplicate of #295

**Comment by andlabs** [comment]
Duplicate of #230
