### ISSUE TITLE
Progressbar not updating from go routine?

### ISSUE THREAD

**Issue by philiplb** [andlabs/ui#298]
Hi,
my progressbar just gets stuck here with zero progress. Do you know why?

```go
type progress func(current, total int)

func foo(p progress) {
	go func() {
		for i := 1; i <= 100; i++ {
			time.Sleep(100 * time.Millisecond)
			p(i, 100)
		}
	}()
}


myButton.OnClicked(func(button *ui.Button) {
	button.Disable()
	foo(func(current, total int) {
		value := int(float64(current) / float64(total) * 100.0)
		progressBar.SetValue(value)
	})
	button.Enable()
})
```
Strange: Also the button doesn't get disabled?

If this pattern doesn't work at all, how would you recommend to have a heavy function reporting progress to the UI without blocking it?

**Comment by andlabs** [comment]
Correct; you can't update the progressbar from another goroutine. You can call `ui.QueueMain()`, which will cause the function you pass in to be run on the main goroutine; it returns immediately, so you can continue your work.

**Comment by philiplb** [comment]
That works fine, thank you! :)
For the button-issue: I will open another issue as it seems to be something different.

**Comment by hairichuhe** [comment]
I have  a problem like this,how can I write this with chan
 `
var cnum = make(chan int, 8)
var pbc = make(chan int)
generatebutton.OnClicked(func(*ui.Button) {
			generatebutton.Disable()
			pbar.Show()
			checkProgress(func(current, total int) {
				ui.QueueMain(func() {
					value := int(float64(current) / float64(total) * 100.0)
					pbar.SetValue(value)
					if current == total {
						generatebutton.Enable()
						pbar.Hide()
					}
				})
			})
			for i := 0; i < num; i++ {
				cnum <- 1
				go createqrcode()
			}
		})
func createqrcode() {
	time.Sleep(400 * time.Millisecond)
	<-cnum
	pbc <- 1
}

type progress func(current, total int)

func checkProgress(p progress) {
	go func() {
		for i := 1; i <= num; i++ {
			<-pbc
			fmt.Println(i)
			p(i, num)
		}
	}()
}`
