### ISSUE TITLE
Error go get andlabs/ui  - undefined reference to `__imp_TaskDialog'

### ISSUE THREAD

**Issue by sgtram** [andlabs/ui#304]
` $ go get github.com/andlabs/ui
# github.com/andlabs/ui
C:/go/src/github.com/andlabs/ui/libui_windows_amd64.a(stddialogs.cpp.obj): In function `msgbox':
E:/github.com/andlabs/libui/windows/stddialogs.cpp:113: undefined reference to `__imp_TaskDialog'
collect2.exe: error: ld returned 1 exit status`

Windows 10 Pro x64

**Comment by andlabs** [comment]
Duplicate of #279
