### ISSUE TITLE
Get Float64 value in SpinBox

### ISSUE THREAD

**Issue by DanielSokil** [andlabs/ui#312]
What is the best way to get a float64 value? I have tried using SpinBox.

**Comment by andlabs** [comment]
Spinbox currently does not support float64, only int64. You can use a normal text box with package `strconv` in the interim.

**Comment by DanielSokil** [comment]
Thanks for the pointer.

**Comment by andlabs** [comment]
You shouldn't be ignoring errors from strconv. Package ui does need better validation primitives, though... (That's in the backlog.)
