### ISSUE TITLE
Build failing on High Sierra

### ISSUE THREAD

**Issue by ajwillia-ms** [andlabs/ui#313]
On 10.13.6 I see the following error

➜  ui git:(master) go build        
go build github.com/andlabs/ui: invalid flag in #cgo LDFLAGS: -mmacosx-version-min=10.8

If I remove the -mmacosx-version-min from link_darwin_amd64.go the build succeeds.

**Comment by andlabs** [comment]
Duplicate of golang/go#23749. Update your Go.

**Comment by ajwillia-ms** [comment]
Thank you for that - I had not noticed that the cgo updated covered the mac specifics.
Updating to 1.10.3 fixed it.
