### ISSUE TITLE
无聞老師教程3 run bee beeblog

### ISSUE THREAD

**Issue by kcscan** [andlabs/ui#314]
$ bee run beeblog
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0
2018/08/23 02:27:04 INFO     ▶ 0001 Using 'beeblog' as 'appname'
2018/08/23 02:27:04 INFO     ▶ 0002 Initializing watcher...
# beeblog
D:\Go\pkg\tool\windows_386\link.exe: running gcc failed: exit status 1
gcc: fatal error: -fuse-linker-plugin, but liblto_plugin-0.dll not found
compilation terminated.

2018/08/23 02:27:07 ERROR    ▶ 0003 Failed to build the application: # beeblog
D:\Go\pkg\tool\windows_386\link.exe: running gcc failed: exit status 1
gcc: fatal error: -fuse-linker-plugin, but liblto_plugin-0.dll not found
compilation terminated.

**Comment by andlabs** [comment]
I do not know what this is, but from the error message, it is not a problem with package ui.

**Comment by kcscan** [comment]
idex.ptl改成home.html 類型卻是 TPL檔案  會不會錯在這邊?

**Comment by kcscan** [comment]
我是新手,看无聞老師的課程學到Go Web基礎第3課
在Git Bash下執行bee run beeblog發生以下錯誤
$ bee run beeblog
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0
2018/08/23 23:59:42 INFO     ▶ 0001 Using 'beeblog' as 'appname'
2018/08/23 23:59:42 INFO     ▶ 0002 Initializing watcher...
2018/08/23 23:59:44 ERROR    ▶ 0003 Failed to build the application: # beeblog
D:\Go\pkg\tool\windows_386\link.exe: running gcc failed: exit status 1
gcc: fatal error: -fuse-linker-plugin, but liblto_plugin-0.dll not found
compilation terminated.
爬了好多文都無法解決,後來安裝MINGW64的Windows 32版
在Run Terminal下執行則成功的在localhost:8080輸出我的博客
我是windows 7 32位元,git version 2.18.0.windows.1,
go version go1.10.3 windows/386
不知是否哪裡出了問題?

**Comment by andlabs** [comment]
This is not the correct place for issues with beego. File your issue at https://github.com/beego/beeblog/issues instead.
这不是beego问题的正确位置。 请在https://github.com/beego/beeblog/issues上提交您的问题。

(note: translated with google translate)
