### ISSUE TITLE
go get FAIL

### ISSUE THREAD

**Issue by Billchen28** [andlabs/ui#317]
Ubuntu 18.04.1 LTS
x86_64-linux-gnu-ld:
github.com/andlabs/ui/libui_linux_amd64.a(libui-combined.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
Linux version 4.15.0-30-generic (buildd@lgw01-amd64-060) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3))

**Comment by philiplb** [comment]
This is a duplicate of https://github.com/andlabs/ui/issues/230 and I solved it with the there proposed recompilation of the alpha3.5 of libui:
```bash
git clone git@github.com:andlabs/libui.git
cd libui/
git checkout alpha3.5
mkdir build
cd build/
cmake -DBUILD_SHARED_LIBS=OFF ..
make
cp out/libui.a /home/.../go/pkg/github.com/andlabs/ui/libui_linux_amd64.a
```

**Comment by andlabs** [comment]
Duplicate of #230
