### ISSUE TITLE
collect2.exe: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by leeyuanzhang** [andlabs/ui#319]
# github.com/andlabs/ui

Go get github.com/andlabs/ui
After trying to run, I get the following error

```
D:/Users/sammy Lee/Miniconda2/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find D:/Users/sammy: No such file or directory
D:/Users/sammy Lee/Miniconda2/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find Lee/Miniconda2/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/lib/../lib/default-manifest.o: No such file or directory
collect2.exe: error: ld returned 1 exit status
```

**Comment by andlabs** [comment]
You'll need to go get the `winmanifest` subpackage too.

**Comment by sheppe** [comment]
I'm getting this error on Windows 10 64-bit. Here's the gcc -v output:

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/5.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-5.1.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 5.1.0 (tdm64-1)

**Comment by andlabs** [comment]
It appears MinGW does not like having spaces in its directory name.

**Comment by sheppe** [comment]
>           It appears MinGW does not like having spaces in its directory name.

You're correct, which is why there are no spaces in its install path.

**Comment by andlabs** [comment]
@sheppe that is the problem in the original post. Your error is likely different; can you post it?

**Comment by sheppe** [comment]
c:/mypath/go/src/github.com/andlabs/ui/libui_windows_amd64.a(stddialogs.cpp.obj): In function `msgbox':
C:/projects/libui/windows/stddialogs.cpp:113: undefined reference to `__imp_TaskDialog'
collect2.exe: error: ld returned 1 exit status

**Comment by andlabs** [comment]
@sheppe that's #279
