### ISSUE TITLE
table reload

### ISSUE THREAD

**Issue by BOPsemi** [andlabs/ui#333]
I would like to reload table view after data update, do you have any idea to do that ?
I had already tried to do that by hide()->show(), but this one didn't work

**Comment by bcampbell** [comment]
You need to call `RowInserted()`, `RowChanged()` and `RowDeleted()` on the TableModel to tell it about each change you make to the data. There's nothing at the moment to do any sort of bulk update or to replace the data en mass... (the underlying libui code doesn't support this either).

**Comment by BOPsemi** [comment]
Hello All,
Thanks for your advice !!
