### ISSUE TITLE
run error in windows

### ISSUE THREAD

**Issue by yunyanU** [andlabs/ui#368]
# github.com/andlabs/ui
D:/GoPATH/pkg/mod/github.com/andlabs/ui@v0.0.0-20180902183112-867a9e5a498d/libui_windows_amd64.a(stddialogs.cpp.obj): In function `msgbox':
C:/projects/libui/windows/stddialogs.cpp:113: undefined reference to `__imp_TaskDialog'
collect2.exe: error: ld returned 1 exit status

**Comment by andlabs** [comment]
Update your MinGW-w64.

**Comment by zhang-ray** [comment]
I got a similar error:
```
# github.com/andlabs/ui
C:/Users/root/go/pkg/mod/github.com/andlabs/ui@v0.0.0-20180902183112-867a9e5a498d/libui_windows_amd64.a(stddialogs.cpp.obj): In function `msgbox':
C:/projects/libui/windows/stddialogs.cpp:113: undefined reference to `__imp_TaskDialog'
collect2.exe: error: ld returned 1 exit status
```

**Comment by andlabs** [comment]
@zhang-ray update your MinGW-w64

**Comment by zhang-ray** [comment]
> @zhang-ray update your MinGW-w64

Hello @andlabs , could you please give me more instruction? My GCC was installed from TDM-GCC JUST two days ago...

**Comment by andlabs** [comment]
Yes, and that proves that TDM-GCC is outdated. You'll need to use [MinGW-w64](http://mingw-w64.org/) instead.

**Comment by sanguohot** [comment]
@andlabs Thanks. My problem is solved after I changed `TDM-GCC` to `MinGW`
