### ISSUE TITLE
how can I hide the console

### ISSUE THREAD

**Issue by dylanliang** [andlabs/ui#37]
the hello  example
win7 compiled the exe file and exec it will open a console ... how to hide it

**Comment by andlabs** [comment]
[Possible alternative](http://msdn.microsoft.com/en-us/library/windows/desktop/ms683150%28v=vs.85%29.aspx)

I'm not sure if I want to do this, however, as
a) that would leave stdin/stdout/stderr dangling
b) I don't know if calling this function on a linked-as-console program would kill that program
Still a possibility.

**Comment by andlabs** [comment]
Merging this issue with #90.
