### ISSUE TITLE
Request: OnDoubleClick(f func) and Table.HighLight(index int)

### ISSUE THREAD

**Issue by vhakulinen** [andlabs/ui#39]
Would love to see these two methods on table:

Table.OnDoubleClick(f func); just like the Table.OnSelected() but for double click.

Table.HighLight(index i); highlight item in index.

**Comment by andlabs** [comment]
Once I can implement accessibility for it the Table rewrite on Windows will be ready to go. Hopefully by the end of the month this issue can be closed.

**Comment by andlabs** [comment]
Status update: read [this comment](https://github.com/andlabs/ui/issues/31#issuecomment-75396861). Then:

**OnDoubleClick()** - will be decided when I do the new backend. I'm not sure if I'll cal this `OnRowActivated()` and provide an `ActivatesOnSingleClick` property or not.

**SetBackgroundColor()** - will definitely be much easier with a model-based setup. The only other problem is how to specify colors: would I be able to do alpha-blendied colors (where the alpha blend is to the background color on Windows) or not? Next comments will contain notes.

**Comment by andlabs** [comment]
Replaced with andlabs/libui#310 (highlight is already in the new table code that I have, though).
