### ISSUE TITLE
Table column name and column width

### ISSUE THREAD

**Issue by SweetDevil** [andlabs/ui#40]
HI , 
first forgive me my english is not good.
I get a problem with Table is that Table column display name is based on struct field name, but my mother tongue is not English.
so is there anyway to change table column display name to display non english character.

type Column struct{
      Name  string
      Age     string //but i thought int need be surpport
}

and table column display Name,Age,i want to display 姓名,年龄
maybe struct tag `display:"姓名"` is a way
![qq 20141016101113](https://cloud.githubusercontent.com/assets/6388324/4656745/c05699b0-54dc-11e4-9827-b0e56e653112.jpg)

by the way,how to set button height and width,
thanks!

**Comment by andlabs** [comment]
Once I can implement accessibility for it the Table rewrite on Windows will be ready to go. Hopefully by the end of the month this issue can be closed.

**Comment by andlabs** [comment]
Added the column header text feature.

What do you mean by setting button width and height? What do you want to do?

**Comment by andlabs** [comment]
Replaced with andlabs/libui#310.
