### ISSUE TITLE
documentation and examples

### ISSUE THREAD

**Issue by Jarema** [andlabs/ui#41]
in Your readme You state that You're open to new feature requests.

I have one. Quite boring, but it can help improve this repository, and make it even more popular.
DOCS! :)

The wiki getting started guide is excellent(both form and content),  but wiki itself is lacking. It even states, that more advanced examples are elsewhere, but they're nowhere there.

Such a moment - not being sure what HAVE to be done next is usually a good one to fill the docs, wiki, and examples while waiting for some enlightment or great ideas. Especially when so much work was already (I'm referring to godoc now).

Even such a simple thing as linking https://godoc.org/github.com/andlabs/ui in readme file would be as simple, as nice  and useful.

**Comment by andlabs** [comment]
Merged with andlabs/libui#317.
