### ISSUE TITLE
Avoid cgo

### ISSUE THREAD

**Issue by pjebs** [andlabs/ui#416]
Is there a way to not rely on cgo?

**Comment by CheatCoder** [comment]
No there is no way, go have no gui buildin and you can't build one with pure c.

Look at other guis like fyne or something.

All need c to build the gui.

Greets.

**Comment by andlabs** [comment]
Correct. While you can get far on Windows without cgo, there unfortunately is currently no way to avoid cgo on other platforms. Maybe at some point it'll be possible to have an API like Windows's syscall.DLL and this will be more possible (though how much depends on the intricacies of calling conventions and structure layouts), but that's a question for the Go team.
