### ISSUE TITLE
feature request: OpenGL support

### ISSUE THREAD

**Issue by notnot** [andlabs/ui#48]
Support the creation of OpenGL contexts.

**Comment by sharpner** [comment]
+1

**Comment by hajimehoshi** [comment]
+1

**Comment by andlabs** [comment]
Wayland support will require GTK+ 3.8. Please see [this](https://github.com/andlabs/ui/issues/87) unless you want X11-only OpenGL for now.

**Comment by andlabs** [comment]
Merged with andlabs/libui#34.
