### ISSUE TITLE
support iOS?

### ISSUE THREAD

**Issue by wangkuiyi** [andlabs/ui#64]
It is exciting to see that Go can inter-operate Objective-C objects. Is it possible for ui to support iOS using https://bitbucket.org/minux/goios/wiki/Home?

**Comment by andlabs** [comment]
timeliness update: golang.org/x/mobile seems to be live; still not sure how one would integrate accessing the native GUI toolkit in Android and integrating it with the app model or however you call it. We'll have to wait for iOS, maybe??

**Comment by 1l0** [comment]
:+1:

**Comment by sndnvaps** [comment]
Can it support arm platform . such as Raspberry PI

**Comment by andlabs** [comment]
Yes, I just need an ARM environment I can emulate on this computer so I can build the binaries.

**Comment by sndnvaps** [comment]
but still need to install libgtk-3-dev for it. 

apt-get install libgtk-3-dev

**Comment by sndnvaps** [comment]
i will test it on the latest build of ubuntu mate of raspberry pi 2

**Comment by sndnvaps** [comment]
ok ,it work on Raspberry Pi 2, with gtk+-3.0 support

**Comment by andlabs** [comment]
Merged with andlabs/libui#327.
