### ISSUE TITLE
Feature request: control over message pump, i.e. "idle" callback

### ISSUE THREAD

**Issue by JamesDunne** [andlabs/ui#68]
I'm working on a simulator app that needs to take control over the message pump in order to simulate while otherwise "idle", i.e. no messages coming through to process. Timer messages via the message pump don't quite cut it here. The simulation has to be done as part of the message pump loop so as to utilize max CPU.

I've got my simulator implemented in C targeting the Win32 API, having a main message pump using PeekMessage instead of GetMessage so as not to block. I'd love to be able to port my simulator to Go so I can run it on Windows and OS X using your UI framework to bridge the gap. I would fork your repo myself and make the change but I only know how to do this for Win32, not for OS X.

**Comment by andlabs** [comment]
Technically that's what `ui.Do()` does already, except it does a full message post (not a `PeekMessage()` loop) and uses Grand Central Dispatch on OS X because I didn't want to reimplement `[NSApplication run]` and take away functionality by accident... I'll see what else I can do, though, since IDK if I want to split the message loop thread entirely away from Go-land or not

**Comment by JamesDunne** [comment]
// Do performs f on the main loop, as if it were an event handler.
    // It waits for f to execute before returning.
    // Do cannot be called within event handlers or within Do itself.
    func Do(f func()) {...}

The last line there made me conclude that I couldn't use Do for an idle loop callback. It seems like I should be able to though. I'd just write a idle function and end it with a Do invocation, passing the idle function to it, as a goroutine.

Honestly, my simulator is not CPU intensive so it doesn't matter much.

**Comment by andlabs** [comment]
Oh right, I forgot about that. The problem is that `Do` waits for the function to be called. I guess I can add a `DoLater`.

**Comment by JamesDunne** [comment]
Heh. I think a `DoLater` would be just fine. Tossing goroutines into the mix is just asking for trouble here, since it's difficult to reason about m:n threading when you have no control over the mapping between goroutines and threads.

**Comment by andlabs** [comment]
Long done.
