### ISSUE TITLE
Error with widgetgallery example

### ISSUE THREAD

**Issue by metal3d** [andlabs/ui#73]
I just installed ui (really nice, congrats) but there are bugs with the widgetgallery example:

    [widgetgallery (master)]$ go run main.go 
    # command-line-arguments
    ./main.go:40: undefined: readIcons
    ./main.go:43: undefined: icon
    ./main.go:48: undefined: tileImage

And, effectually, those functions and vars are not defined :)

**Comment by metal3d** [comment]
My bad... that's all on icons.go... I only had to build... sorry for that...

**Comment by andlabs** [comment]
You're not the first one; maybe I should drop a README there to be safe...
