### ISSUE TITLE
List of available widgets

### ISSUE THREAD

**Issue by metal3d** [andlabs/ui#74]
Maybe somewhere... you could but the list of available/unavailables/featured widgets

A simple list as:
- [x] window
- [x] button
- [x] label
- [x] table
- [ ] splitter

Wikipage ? :)

**Comment by andlabs** [comment]
Not sure how this would be done apart from the documentation, which by its nature will have such a list; that is now being tracked at andlabs/libui#317.

As for the controls not implemented, splitter is now andlabs/libui#319.

On those notes, closing.
