### ISSUE TITLE
Feature request : Javafx like functionality

### ISSUE THREAD

**Issue by fithisux** [andlabs/ui#76]
Describe the UI as an XML and generate golang code.

You asked for a feature request :-)

**Comment by andlabs** [comment]
I forget if this was discussed before here or not (it may have been on IRC) but: it'll come at some point in the future (probably when everything's more refined and I possibly loosen some of the restrictions), and will be a sub-package (i.e. `github.com/andlabs/ui/builder` or something)

**Comment by sinni800** [comment]
I already described something like this in https://github.com/andlabs/ui/issues/42

**Comment by andlabs** [comment]
Merged with #276.
