### ISSUE TITLE
Widget disable event

### ISSUE THREAD

**Issue by crossle** [andlabs/ui#79]
Button widget support disable and enable event?

**Comment by andlabs** [comment]
`Control.Enable()` and `Control.Disable()` will come soon. (Keep open until then.)

**Comment by crossle** [comment]
Thanks, event mean widget enable or disable.

**Comment by andlabs** [comment]
Enabling and disabling are in libui. I don't think there needs to be an event that is triggered when a control is enabled or disabled; you're the one that enabled/disabled them!
