### ISSUE TITLE
Windows ld.exe cannot find -lmsvcrt

### ISSUE THREAD

**Issue by josephyzhou** [andlabs/ui#81]
Currently I'm testing on Windows 8.1 - 64 and have mingw-64 installed under `c:\program files\mingw-w64\...` 
I'm trying to `go get github.com/andlabs/ui` and am getting this error:

```
C:/Program Files/mingw-w64/x86_64-4.9.2-posix-seh-rt_v3-rev1/mingw64/bin../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmsvcrt
collect2.exe: error: ld returned 1 exit status
```

**Comment by josephyzhou** [comment]
Fixed the problem with TDM-GCC!

**Comment by Fruchtgummi** [comment]
I have the same problem with TDM-GCC!

`# github.com/andlabs/ui
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lui
collect2.exe: error: ld returned 1 exit status`

**Comment by ghiewa** [comment]
I either. much MinW?
