### ISSUE TITLE
Install on OSX

### ISSUE THREAD

**Issue by rmasci** [andlabs/ui#82]
I tried to install on OS X and I have the following:

[Mac ~/] $  go install github.com/andlabs/ui
github.com/andlabs/ui
./delegate_darwin.go:93: undefined: s
./delegate_darwin.go:93: cannot assign to s.resizes
./delegate_darwin.go:93: undefined: s
./delegate_darwin.go:94: undefined: s
./delegate_darwin.go:94: undefined: width
./delegate_darwin.go:94: undefined: height
./delegate_darwin.go:94: undefined: s
./delegate_darwin.go:95: undefined: s
./objc_darwin.go:18: cannot use _Cfunc_objc_getClass(cclass) (type C.Class) as type C.id in return argument
[Mac ~/] $ go version
go version go1.4.2 darwin/amd64
[Mac ~/] $

**Comment by andlabs** [comment]
You somehow have a really old version of package ui there. When and how did you get it?

**Comment by rmasci** [comment]
I just did as the command line states: 'go install github.com/andlabs/ui'

**Comment by rmasci** [comment]
OK I downloaded the zip file and installed it that way.  Issue resolved -- with the exception you can't go install it... :D

**Comment by andlabs** [comment]
How did you download it originally? `go install` happens *after* you download it, and `go get` automatically does a `go install`.

**Comment by rmasci** [comment]
All I typed was go install.

**Comment by andlabs** [comment]
If you used `go install` then you would have needed ui in your $GOPATH to begin with. Did you not explicitly get it before? If you got it from some other website, I'd like to know so I can handle things and prevent future mistakes with other people.

**Comment by rmasci** [comment]
I must have tried it a long time ago and didn't realize it... anyway I
uninstalled and reinstalled... go get doesn't work, but when I issue a go
install after the go get it does install:

rmasci@rm-MacMini ~] $ go get github.com/andlabs/ui
# github.com/andlabs/ui
go/src/github.com/andlabs/ui/basicctrls_darwin.m:280:9: warning: returning
'const char *' from a function with result type 'char *' discards
qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
# github.com/andlabs/ui
go/src/github.com/andlabs/ui/dialog_darwin.m:24:4: warning: implicit
declaration of function 'finishOpenFile' is invalid in C99
[-Wimplicit-function-declaration]
# github.com/andlabs/ui
go/src/github.com/andlabs/ui/spinbox_darwin.m:48:19: warning: local
declaration of 'minimum' hides instance variable [-Wshadow-ivar]
go/src/github.com/andlabs/ui/spinbox_darwin.m:49:19: warning: local
declaration of 'maximum' hides instance variable [-Wshadow-ivar]
go/src/github.com/andlabs/ui/spinbox_darwin.m:50:17: warning: incompatible
integer to pointer conversion sending 'NSInteger' (aka 'long') to parameter
of type 'id' [-Wint-conversion]
/System/Library/Frameworks/AppKit.framework/Headers/NSDictionaryController.h:23:22:
note: passing argument to parameter 'value' here
go/src/github.com/andlabs/ui/spinbox_darwin.m:52:31: warning: sending
'goSpinbox *' to parameter of incompatible type 'id<NSTextFieldDelegate>'
/System/Library/Frameworks/AppKit.framework/Headers/NSTextField.h:35:44:
note: passing argument to parameter 'delegate' here
go/src/github.com/andlabs/ui/spinbox_darwin.m:61:16: warning: local
declaration of 'value' hides instance variable [-Wshadow-ivar]
go/src/github.com/andlabs/ui/spinbox_darwin.m:86:17: warning: incompatible
integer to pointer conversion sending 'NSInteger' (aka 'long') to parameter
of type 'id' [-Wint-conversion]
/System/Library/Frameworks/AppKit.framework/Headers/NSDictionaryController.h:23:22:
note: passing argument to parameter 'value' here
go/src/github.com/andlabs/ui/spinbox_darwin.m:92:17: warning: incompatible
integer to pointer conversion sending 'NSInteger' (aka 'long') to parameter
of type 'id' [-Wint-conversion]
/System/Library/Frameworks/AppKit.framework/Headers/NSDictionaryController.h:23:22:
note: passing argument to parameter 'value' here
go/src/github.com/andlabs/ui/spinbox_darwin.m:59:29: warning: conflicting
parameter types in implementation of 'setValue:': 'id' vs 'NSInteger' (aka
'long') [-Wmismatched-parameter-types]
/System/Library/Frameworks/AppKit.framework/Headers/NSDictionaryController.h:23:22:
note: previous definition is here
go/src/github.com/andlabs/ui/spinbox_darwin.m:124:33: warning: incompatible
integer to pointer conversion sending 'NSInteger' (aka 'long') to parameter
of type 'id' [-Wint-conversion]
/System/Library/Frameworks/AppKit.framework/Headers/NSDictionaryController.h:23:22:
note: passing argument to parameter 'value' here
# github.com/andlabs/ui
go/src/github.com/andlabs/ui/uitask_darwin.m:32:24: warning: instance
method '-doKeyDown:' not found (return type defaults to 'id')
[-Wobjc-method-access]
go/src/github.com/andlabs/ui/uitask_darwin.m:32:13: warning: incompatible
pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from
'id' [-Wint-conversion]
go/src/github.com/andlabs/ui/uitask_darwin.m:35:24: warning: instance
method '-doKeyUp:' not found (return type defaults to 'id')
[-Wobjc-method-access]
go/src/github.com/andlabs/ui/uitask_darwin.m:35:13: warning: incompatible
pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from
'id' [-Wint-conversion]
go/src/github.com/andlabs/ui/uitask_darwin.m:38:24: warning: instance
method '-doFlagsChanged:' not found (return type defaults to 'id')
[-Wobjc-method-access]
go/src/github.com/andlabs/ui/uitask_darwin.m:38:13: warning: incompatible
pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from
'id' [-Wint-conversion]
go/src/github.com/andlabs/ui/uitask_darwin.m:30:12: warning: 28 enumeration
values not handled in switch: 'NSLeftMouseDown', 'NSLeftMouseUp',
'NSRightMouseDown'... [-Wswitch]
go/src/github.com/andlabs/ui/uitask_darwin.m:104:21: warning: sending
'appDelegateClass *' to parameter of incompatible type
'id<NSFileManagerDelegate>'
/System/Library/Frameworks/Foundation.framework/Headers/NSFileManager.h:109:47:
note: passing argument to parameter 'delegate' here
[rmasci@rm-MacMini ~] $ go install github.com/andlabs/ui
[rmasci@rm-MacMini ~] $ ls go/pkg/darwin_amd64/github.com/andlabs/ui.a
go/pkg/darwin_amd64/github.com/andlabs/ui.a
[rmasci@rm-MacMini ~] $

On Sun, Mar 22, 2015 at 10:15 PM, Pietro Gagliardi <notifications@github.com

**Comment by andlabs** [comment]
Actually `go get` did work; all you're seeing is a bunch of warnings from the Objctive-C compiler that I need to fix sometime (they shouldn't affect programs made with the package, though).

**Comment by variadico** [comment]
For anyone looking at this in February 2016, this is how I managed to install on OS X.

```shell
# Build libui
git clone git@github.com:andlabs/libui.git
cd libui
gnumake

# Install ui Go package
go get -d github.com/andlabs/ui
cd $GOPATH/src/github.com/andlabs/ui
cp ~/git/libui/ui.h .
cp ~/git/libui/out/libui.A.dylib libui.dylib
go install

# Build an app
cd $GOPATH/src/myapp
cp ~/git/libui/out/libui.A.dylib .
go build
```

**Comment by rmasci** [comment]
Great!! it now compiles on Go ... Any idea how to cross-compile for other
platforms?   There is a tool that I built in Go that needs a GUI, and I
don't want to do the work to build the gui and find out I can't cross
compile it, or that I have to create development environments on Windows.

Thanks,

**Comment by variadico** [comment]
I haven't tried it, but I doubt you'll be able to cross compile this. I can't see `libui.A.dylib` working on anything else except OS X. Also, I'm pretty sure we won't be able to compile any of the C code that includes `uipriv_windows.h`, for example.

At best, you'll have to create VMs for the other platforms and compile natively there.

**Comment by andlabs** [comment]
For GTK+ and OS X you can cross-compile if you have a cross-compilation environment set up by assigning the standard `$CC/$CXX/$LD` variables and specifying `OS=whatever` on the `make` line.

Windows right now requires MSVC.

**Comment by andlabs** [comment]
I'm going to assume this issue was resolved ages ago. Cross-compiling is a separate issue, but not one specific to package ui...

**Comment by rmasci** [comment]
Yes I got it to compile on my mac. Using a virtual machine I was able to
get it compiled for windows too. Thanks!!
