### ISSUE TITLE
Table float values not showing correctly.

### ISSUE THREAD

**Issue by defcronyke** [andlabs/ui#84]
Hi,

Is there some way to make the float values show? Instead of showing the value, it shows "&lt;float64 Value&gt;".

Also, is there a way to disable a checkbox, so that the user may see if it's checked or not, but is not able to toggle it?

Thanks in advance, this library is awesome!

**Comment by andlabs** [comment]
I'm not sure why that does that; I thought I handled non-`string` types correctly in my code... Will definitely need to look into that once I reach the Table portion of the rewrite, so keep this issue open.

The disabled checkboxes are implemented in http://github.com/andlabs/wintable, which package ui will use once it becomes stable. The way to specify that a column of checkboxes should be disabled will need to be added to the package, but that shouldn't be difficult.

**Comment by defcronyke** [comment]
I fixed the float64 and float32 display on unix, see: https://github.com/andlabs/ui/pull/85
Pull if you want, or fix it in your own way. Thanks again.

**Comment by andlabs** [comment]
No longer relevant; a new table system is implemented. All text cells must be strings, and there is wiggle room for more custom formatting options.
