### ISSUE TITLE
ui.Checkbox.OnToggled callback should get a *ui.Checkbox param

### ISSUE THREAD

**Issue by defcronyke** [andlabs/ui#86]
IMHO, this would make it easier to use, for example:

some_checkbox := ui.NewCheckbox("bland clam")
some_checkbox.OnToggled(func() {
    // I want access to the checkbox that was checked here, so I can use Checked() and SetChecked() on it. 
    // It could be a param passed to this closure.
})

**Comment by andlabs** [comment]
In libui. Keep this open for the ui rewrite.

**Comment by andlabs** [comment]
Done.
