### ISSUE TITLE
Controls become blank when moving the window

### ISSUE THREAD

**Issue by ismlsmile** [andlabs/ui#88]
I am running the sample app on Windows, when I move the window, the controls become blank. It seems  like a refresh problem.

**Comment by andlabs** [comment]
I believe I have fixed this problem in libui, but I've never heard of it happening when the window moves... Does the window blank out and you have to mouse over the controls to get them back?

**Comment by hasanyasin** [comment]
Yes, that is exactly what happens. You move or resize the window and the contents of the window are not rendered until you move your mouse over them. I confirm this behavior with the sample greetings application in the repository.

**Comment by omarpta** [comment]
I tested with the "widgetgallery" example on Windows 8.1 and this is really happening,

**Comment by andlabs** [comment]
Yes, thanks. I believe I have fixed the problem in libui, which will replace package ui's backend code once complete enough. Keep this bug open until then.

**Comment by yg7001** [comment]
Good job! expect that new backend too.

**Comment by Programming4life** [comment]
@andlabs libui what commit did you solve this in?

**Comment by andlabs** [comment]
@Programming4life https://github.com/andlabs/libui/commit/2968d48d9e9262ac532d826131db9444a1bef086 basically instead of drawing the parent's background ourselves and having WM_CTLCOLORSTATIC return the hollow brush, we have WM_CTLCOLORSTATIC return a brush containing the parent's background

**Comment by Russtopia** [comment]
Glad to hear this is being worked on. Also affects me on Win7-amd64. Great work. I've just discovered Go and am happy it's getting some UI love. This language kicks so much arse it isn't funny.

Death to C++!. :p

**Comment by andlabs** [comment]
The new backend has been in place for a while now. It has other redraw issues, but not related to this (this fix turns out to be inefficient). Closing.
