### ISSUE TITLE
Error in run program windows 7 - 64bit

### ISSUE THREAD

**Issue by myalexer** [andlabs/ui#91]
Hello
i install win-builds on windows and update all packages - also MinGW and gcc are installed in my os
in cmd i go to examples\widgetgallery then type go build , after a few second it return error : 

# github.com/andlabs/ui
..\..\comctl32_windows.c: In function 'initCommonControls':
..\..\comctl32_windows.c:123:22: warning: assignment from incompatible pointer t
ype
  fv__TrackMouseEvent = (HIMAGELIST (*WINAPI)(int, int, UINT, int, int)) f;
                      ^
# github.com/andlabs/ui
..\..\table_windows.c: In function 'doInitTable':
..\..\table_windows.c:13:12: warning: passing argument 1 of 'initTable' from inc
ompatible pointer type
  initTable(xpanic, fv__TrackMouseEvent);
            ^
In file included from ..\..\table_windows.c:6:0:
..\..\wintable/main.h:144:6: note: expected 'void (*)(const char *, DWORD)' but
argument is of type 'void (*)(char *, DWORD)'
 void initTable(void (*panicfunc)(const char *msg, DWORD lastError), BOOL (*WINA
PI tme)(LPTRACKMOUSEEVENT))

why? i want help

**Comment by andlabs** [comment]
These are all compiler warnings, simple `const` disagreement in the C code. They shouldn't be blocking the build...

**Comment by andlabs** [comment]
No longer relevant to the current version of package ui.
