### ISSUE TITLE
go1.4.2 Error

### ISSUE THREAD

**Issue by 631768417** [andlabs/ui#94]
gook\main.go:4: import C:\GOPATH\pkg\windows_amd64/github.com/andlabs/ui.a: obje
ct is [windows amd64 go1.4rc2 X:precisestack] expected [windows amd64 go1.4.2 X:
precisestack]

**Comment by andlabs** [comment]
You need to rebuild your packages somehow; they're still tied to an older version. I'm not sure why Go isn't rebuilding them automatically for you.

**Comment by andlabs** [comment]
Go 1.4.2 is no longer supported; closing.
