### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by coramo** [andlabs/ui#95]
This is great project .

I learn `golang` language 5 days ,i'm trying to use `go get github.com/andlabs/ui` to install the package ,but i get something wrong .

```
package github.com/andlabs/ui
	imports runtime: C source files not allowed when not using cgo: atomic_386.c defs.c 
float.c heapdump.c lfstack.c malloc.c mcache.c mcentral.c mem_darwin.c mfixalloc.c 
mgc0.c mheap.c msize.c os_darwin.c panic.c parfor.c proc.c runtime.c signal.c 
signal_386.c signal_unix.c stack.c string.c sys_x86.c vlrt.c
import cycle not allowed
package github.com/andlabs/ui
	imports runtime/cgo
	imports runtime/cgo
```

My environment : 
- Mac OS X 10.10.3
- Xcode6.3.2 And installed Command Line Tool
- go 1.4.2 64bit

I'm not sure this is my fault. but please help me.
Thanks. - -

**Comment by andlabs** [comment]
Your Go installation is broken somehow. It's trying to use cgo but you don't have cgo enabled. How did you build your Go?

**Comment by coramo** [comment]
Thanks for you prompt, i fixed this issues .

It's because i set the `GOROOT` is wrong. i reset the path .now, it's work.
