### ISSUE TITLE
Add MessageBox/JOptionPane

### ISSUE THREAD

**Issue by jimfwirth** [andlabs/ui#96]
Nice CLEAN API - KUDOS
Is there an equivalent to popup dialogs, e.g:  MessageBox(mswin)/JOptionPane(java) yet?

**Comment by andlabs** [comment]
That is in libui. Right now only OK message boxes with no icon and with an error icon are supported. In the future I'll add Yes/No, Save/Discard/Cancel, and a few others.

**Comment by jimfwirth** [comment]
Thanks,
Will wait semi-patiently
I have several questions off topic - is there a back channel to talk to you or should I just raise them
as issues???
I am a github NEWBY and do not know acceptable protocols

**Comment by jimfwirth** [comment]
In re "OK message boxes" have grepped -r around the ui package sources for MessageBox, MsgBox, Popup, etc. and cannot find the API for such a thing.  Also scrutinized https://godoc.org/github.com/andlabs/ui looking for the same.
No doubt have missed something obvious.

**Comment by andlabs** [comment]
The message boxes are not implemented in package ui yet.

**Comment by andlabs** [comment]
Closing as part of migration of feature requests to libui.
