### ISSUE TITLE
Panic on Windows

### ISSUE THREAD

**Issue by krolaw** [andlabs/ui#97]
Probably won't garner much interest as the lib is being rewritten, but if there is, I'll look at putting together a simple example.

panic: error getting DC for preferred size calculations: Invalid window handle.

goroutine 1 [running, locked to thread]:
github.com/andlabs/ui.xpanic(0x747c48, 0x578)
        C:/Users/Patrick/go/src/github.com/andlabs/ui/common_windows.go:17 +0x13
7
github.com/andlabs/ui._Cfunc_calculateBaseUnits(0x4, 0x126b7ea0, 0x126b7e9c, 0x1
26b7e98)
        C:/Users/Patrick/go/src/github.com/andlabs/ui/:188 +0x3f
github.com/andlabs/ui.beginResize(0x4, 0x12721a60)
        C:/Users/Patrick/go/src/github.com/andlabs/ui/container_windows.go:53 +0
x6c
github.com/andlabs/ui.windowResize(0x12720f60, 0x18fc98)
        C:/Users/Patrick/go/src/github.com/andlabs/ui/window_windows.go:89 +0x2e

github.com/andlabs/ui._Cfunc_uimsgloop()
        C:/Users/Patrick/go/src/github.com/andlabs/ui/:440 +0x3f
github.com/andlabs/ui.uimsgloop()
        C:/Users/Patrick/go/src/github.com/andlabs/ui/uitask_windows.go:45 +0x1e

github.com/andlabs/ui.Go(0x0, 0x0)
        C:/Users/Patrick/go/src/github.com/andlabs/ui/uitask.go:22 +0x69
main.main()
        C:/Users/Patrick/go/src/pbx/nuideskHelper.go:29 +0xf6

**Comment by andlabs** [comment]
That shouldn't happen; if the window is being closed prematurely then...

**Comment by andlabs** [comment]
No longer relevant to the current version of package ui.
