### ISSUE TITLE
File picker ?

### ISSUE THREAD

**Issue by Depado** [andlabs/ui#98]
Hello,
I've been googling for about an hour now and I must be pretty lame at this because I can't find what I'm looking for.

Is there a way in Go to call the system file chooser (the one that opens a popup and (I guess) returns the full path of the file being chosen) ? I don't even know if the term "file picker" is the correct one. What I'd like to do is click on a button (using ui), open the file picker and return the full path to my go program so I can work on the chosen file. 

Thanks :)

**Comment by andlabs** [comment]
This has already been implemented in libui. Once I can do the OS X backend, I'll release an alpha of that, then an alpha of its Go bindings.

**Comment by Depado** [comment]
Awesome, can't wait for it :)
Thanks for the great work :+1:

**Comment by arpitjindal97** [comment]
I can't find this feature yet

**Comment by andlabs** [comment]
It is still not implemented. Follow #277
